"""Error template data for the WRO error catalog - themes 6..9.

Every template is a tuple:
  SMALL: (error, [terminal lines], what-happened, why-root-cause, fix)
  BIG:   (terminal, error, [terminal lines], what-happened,
          why-root-cause, [investigation steps], fix)
"""

SMALL = {
    6: [
        ("PID output saturates then overcorrects",
         ["$ python3 {file}",
          "output: 0.98 -> -0.99 -> 0.97",
          "robot snakes down the straight"],
         "The robot weaved down the straight at every launch. The PID output swung from full throttle to full brake and back, several times per second.",
         "The integral term accumulated while the robot was stalled at launch, and by the time motion started the integral alone exceeded the output limits. The controller then had to burn off the stored error by overshooting in the opposite direction - classic integral windup. Windup happens because the integrator keeps summing even while the output is clamped at its physical limit, so the error it stores is never realizable.",
         "Fixed by adding anti-windup: stop integrating when the output is saturated and the integral would push it further into the limit."),
        ("Stanley cross-track error is NaN at waypoint 0",
         ["$ python3 {file}",
          "cross_track: nan  (first waypoint)",
          "no steering command sent"],
         "The Stanley controller produced no steering command at the first waypoint. The cross-track error was NaN, so the controller output was NaN, and the car drove straight past the path.",
         "The first path segment had zero length - two identical waypoints at the start of the list - so the tangent direction was undefined, and the cross-track math divided by zero. Stanley's formula assumes a valid segment direction; a zero-length segment violates that invariant. The NaN then propagated through the control output because no validation existed between the path math and the steering command.",
         "Fixed by skipping zero-length segments in the path parser and replacing any NaN cross-track value with the previous valid value."),
        ("Gain schedule jumps at the speed boundary",
         ["$ python3 {file}",
          "gain: 0.9 -> 2.4 (speed 1.00 m/s)",
          "steering step visible in the log"],
         "The steering gain jumped from 0.9 to 2.4 the instant the robot crossed 1 m/s. The steering response suddenly felt twice as aggressive.",
         "The gain schedule was a lookup table with discrete rows, and the lookup switched rows at the boundary instead of interpolating between them. A discontinuous gain produces a discontinuous control law: the controller's personality changes instantly at a speed threshold. Gain scheduling is only smooth when the schedule itself is smooth.",
         "Fixed by linearly interpolating between table rows, and adding a test that verifies the gain never changes by more than 10% per control tick."),
        ("Feedforward sign is opposite on reverse",
         ["$ python3 {file}",
          "reverse + feedforward = wrong direction",
          "robot pulls to the left in reverse"],
         "In reverse, the robot consistently pulled to the left. The feedback controller was compensating correctly - the feedforward term was actively fighting it.",
         "The feedforward steering term was computed for forward motion and applied unchanged when reversing. Steering geometry is direction-dependent: the same curvature requires the opposite steer correction when the velocity is negative. The sign flip was known in the ackermann module but not propagated to the controller, so two modules disagreed about the direction convention.",
         "Fixed by multiplying the feedforward term by the direction sign, and adding a reverse-path test case to the controller test suite."),
        ("Cubic spline overshoots past the goal",
         ["$ python3 {file}",
          "end: x=2.01 y=0.03 (goal 2.00, 0.00)",
          "overshoot 1cm at the parking spot"],
         "The spline ended 1cm past the parking target. Small in absolute terms, fatal for a parking maneuver where the tolerance is measured in millimeters.",
         "The smoothing pass relaxed the endpoint constraints, letting the spline drift off the fixed end point. Splines are defined by their boundary conditions; the endpoint condition was applied before smoothing and the smoother was allowed to move it. The constraint was lost in the pipeline, not in the math.",
         "Fixed by re-imposing the fixed endpoint condition after smoothing and adding a unit test that pins both endpoints to the exact goal."),
        ("Velocity profile outputs negative speeds",
         ["$ python3 {file}",
          "v: -0.2 m/s at t=1.2s",
          "robot reverses mid-run"],
         "The robot briefly reversed in the middle of a straight run. The velocity profile commanded a negative speed - the robot was doing exactly what it was told.",
         "The trapezoidal profile computes the deceleration phase assuming the target is reachable in the given time. When the target was too close for the time budget, the deceleration term overshot below zero. The math produced an unreachable profile instead of detecting the conflict; negative speed is the profile's way of saying 'the plan is impossible'.",
         "Fixed by clamping the profile speed to zero and extending the profile duration when the target is not reachable within the requested time."),
        ("Obstacle avoidance oscillates left-right",
         ["$ python3 {file}",
          "steer: +12 -14 +11 -13 deg",
          "no progress toward the goal"],
         "The robot wobbled in front of an obstacle without making progress. The steering command swung positive and negative every half second.",
         "The avoidance gain and the goal-pull gain fought each other: as the robot turned away from the obstacle it aligned with the goal, and as it turned toward the goal it approached the obstacle again. Two competing controllers with no arbitration produced a limit cycle. The oscillation is the system's equilibrium - it is stable in the wrong way.",
         "Fixed by adding a deadband where neither controller acts and a goal bias that makes the goal-pull dominant whenever both demands conflict."),
        ("MPC solve fails on the first step",
         ["$ python3 {file}",
          "cvxpy error: Problem status INFEASIBLE",
          "no control output"],
         "The model-predictive controller produced no output at all - the solver reported the optimization problem was infeasible at the very first step.",
         "The MPC horizon covered more track than existed, and the terminal constraint required the robot to be at a goal point the path could not reach within the horizon. A constrained optimization with contradictory constraints is infeasible by definition; the solver correctly refused to solve an impossible problem. The model was the bug - the horizon and constraints did not match the track geometry.",
         "Fixed by shrinking the horizon to the track length and relaxing the terminal constraint from an equality to a soft penalty."),
    ],
    7: [
        ("State machine stuck in IDLE",
         ["$ python3 {file}",
          "state: IDLE (30s)",
          "start line never detected"],
         "The robot sat at the start line for 30 seconds and never launched. The start detector was reporting, but the state machine was not listening.",
         "The state machine waited for an event named 'start_detected', but the start detector published 'start_found'. Two modules used different names for the same fact - a vocabulary mismatch, not a logic error. Event-driven systems fail silently when events are named inconsistently, because the missing event simply never arrives.",
         "Fixed by aligning the event names through a shared event constants module, and adding a startup check that logs the events each task publishes."),
        ("Lap counter double counts a lap",
         ["$ python3 {file}",
          "laps: 0 1 2 3 3 4 (double count at 3)",
          "race finished a lap early"],
         "The lap counter logged lap 3 twice, so the robot believed the race ended one lap early. The count went 3, 3 - two events for one crossing.",
         "The lap line check ran on every frame while the robot was on the line, and every frame produced a lap event. There was no state to remember that the line had already been crossed. A threshold crossing is a single event, but a per-frame comparison produces one event per frame - the missing piece is edge detection, not counting.",
         "Fixed by adding a crossed flag that only resets after the robot leaves the line, so one crossing produces exactly one event."),
        ("Start detected on camera noise",
         ["$ python3 {file}",
          "start: DETECTED (t=0.2s)",
          "robot launches before the judge signal"],
         "The robot launched 0.2 seconds after boot - before the judge's signal. A dark frame edge had matched the start pattern.",
         "The start detector was a single-frame pattern match, and a single noisy frame can contain anything. With no confirmation requirement, one false match was enough to launch. Detection systems that decide from one sample have the error rate of one sample; the fix is statistical, not algorithmic - require agreement across time.",
         "Fixed by requiring three consecutive confirmed frames (over 60ms) before launching, and rejecting the first 500ms of camera frames after start."),
        ("Direction is inverted after the first reverse",
         ["$ python3 {file}",
          "direction: forward (robot is reversing)",
          "pillar logic wrong side"],
         "After the first reverse maneuver the robot's direction state said FORWARD while it was physically reversing. All pillar logic that depended on direction was wrong from that moment.",
         "The reverse command was executed by the motor layer, but the direction flag lived in a different module and was never updated when the reverse command ran. Two copies of the truth (the actual motion and the recorded state) diverged, and nothing enforced their consistency. The state was updated at the command level, not at the motion level where the truth exists.",
         "Fixed by updating the direction flag inside the reverse state action, and adding an assertion that compares the flag against the motor layer's reported direction."),
        ("Parking overshoots the zone by 10cm",
         ["$ python3 {file}",
          "final offset: 0.10m  (limit 0.05m)",
          "partial points only"],
         "The parking maneuver stopped 10cm outside the zone - double the allowed tolerance. The robot lost 8 points to the overshoot.",
         "The final correction used the same approach speed as the main run, and the correction controller could not react before the robot rolled through the boundary. Parking corrections operate in millimeters and need low speeds; at the run speed the controller latency alone consumed the tolerance. The speed schedule was one value for all phases, and the parking phase needed a different one.",
         "Fixed by switching to CRAB_WALK for the last 10cm and capping the park approach speed at 0.15 m/s, with the tolerance margin verified in the park_sm test."),
        ("Checkpoint is missed on the fast lap",
         ["$ python3 {file}",
          "checkpoint 2: MISSED",
          "shortcut not detected at speed"],
         "The robot passed through checkpoint 2 at speed and the system never noticed. On slow laps the checkpoint always registered - the miss was speed-dependent.",
         "The checkpoint gate was checked at 10Hz, and at 2m/s the robot crossed the gate in 60ms - faster than the check period. The checker literally never observed the crossing; the event happened between samples. Periodic sampling can only detect events that last longer than the sample period.",
         "Fixed by checking the gate every frame instead of every 100ms, and adding a position interpolation that detects gate crossings between frames."),
        ("Race strategy picks the slow lane",
         ["$ python3 {file}",
          "lane: outer (inner was free)",
          "lost 0.8s per lap"],
         "The race strategy chose the outer lane while the inner lane was clear, losing 0.8 seconds per lap. The choice was stable and consistent - and consistently wrong.",
         "The lane score was computed once before the race and considered only static geometry. The inner lane's obstacle was gone by lap 2, but the score still penalized it. A decision based on stale information is not a strategy error - it is an information freshness error. The strategy answered the question 'which lane was best 2 minutes ago'.",
         "Fixed by recomputing the lane score every lap from the live obstacle state, and logging the score so a wrong choice is visible in the log."),
        ("Reverse logic oscillates at the obstacle",
         ["$ python3 {file}",
          "forward reverse forward reverse ...",
          "robot stuck for 4s"],
         "The robot shuffled forward and backward in front of an obstacle for four seconds. Both directions were correct decisions - in isolation.",
         "The obstacle strategy evaluated the escape direction every frame, and each frame the evaluation flipped: after reversing a bit, the sensor saw a path forward again, and vice versa. A controller without state memory will oscillate whenever the sensor feedback lags the actuator. The hysteresis that exists in wall-following was missing here.",
         "Fixed by adding a minimum dwell time in each direction state (0.5s), so the strategy commits to a direction instead of re-deciding every frame."),
    ],
    8: [
        ("YAML parse error in default_config.yaml",
         ["$ python3 {file}",
          "yaml.scanner.ScannerError: mapping values are not allowed here",
          "config failed to load"],
         "The robot refused to boot because the configuration file could not be parsed. The file looked correct to a human - the colon in a string was the problem.",
         "YAML treats an unquoted colon followed by a space as a key/value separator. A string containing 'mode: fast' inside a value breaks the parser because it sees a nested mapping where it did not expect one. YAML is whitespace- and punctuation-sensitive in ways that are invisible to a quick read, which is why config errors show up at load time, never at edit time.",
         "Fixed by quoting the value, and adding a config validation step at boot that parses the YAML and reports the exact line of any syntax error."),
        ("Surprise rule key is unknown",
         ["$ python3 {file}",
          "KeyError: 'pillar_logic' in surprise_config",
          "rules ignored, defaults used"],
         "The surprise rules loaded without error, but the pillar logic rule never took effect - the robot ran the default behavior all day.",
         "The loader read keys by an explicit allowlist, and 'pillar_logic' was not in it, so the rule was silently dropped. A missing key in a config lookup is a silent failure when the code uses .get() with a default and a crash when it uses [] - this code used a path that neither crashed nor worked. The rules file and the loader schema had drifted apart.",
         "Fixed by adding the key to the loader schema and logging a warning whenever a configured rule key is ignored, so silent drops become visible."),
        ("Steering mode switch race condition",
         ["$ python3 {file}",
          "mode: OPPOSITE (expected CRAB)",
          "one-frame wrong steering at the switch"],
         "For exactly one frame at every mode switch, the robot steered with the wrong geometry. The switch itself worked - the frame in between did not.",
         "The mode flag was written by the mission thread and read by the control thread without synchronization. The control thread could read the flag mid-update, observing a mixed state. A one-frame glitch is exactly what a data race looks like: mostly correct, occasionally wrong, impossible to reproduce on demand.",
         "Fixed by making the mode switch atomic - the mode lives in a single int that the scheduler publishes, and the control thread reads it through a lock-free once-store."),
        ("Heartbeat times out on a busy CPU",
         ["$ python3 {file}",
          "heartbeat lost: 1500ms",
          "motors cut mid-run"],
         "The motors cut out for a moment in the middle of a run, then resumed. The failsafe fired, then recovered on its own - a glitch with consequences.",
         "The heartbeat thread could not get CPU time during perception spikes, so the failsafe correctly concluded the main loop was dead and cut the motors. The failsafe is designed to be conservative: any doubt means stop. The bug was that a healthy but busy system looked dead to the heartbeat - the failure detector could not distinguish 'slow' from 'dead'.",
         "Fixed by raising the heartbeat thread priority and extending the timeout to 2s, with a separate watchdog that only fires when the main loop is truly stuck."),
        ("Health monitor false alarm on sensor 3",
         ["$ python3 {file}",
          "sensor 3: FAIL (3 misses)",
          "actually fine, just slow"],
         "The health monitor declared the ToF dead at every boot. The sensor was alive - it was just slow to warm up, and the monitor did not wait.",
         "The failure threshold was three consecutive misses, and the ToF's warm-up period legitimately produces more than three misses before its first valid reading. The threshold was calibrated against runtime behavior, not boot behavior. A monitor with a fixed threshold cannot distinguish a boot transient from a persistent failure.",
         "Fixed by raising the threshold to 20 misses and adding a warm-up grace period of 5 seconds at boot, matching the measured sensor ready time."),
        ("Track map is off by one section",
         ["$ python3 {file}",
          "section: 5 (expected 4)",
          "strategy picks the wrong corner"],
         "Every lap the track map believed the robot was one section further along than reality. The strategy consistently prepared the wrong corner.",
         "The section counter incremented on both entering and exiting the section boundary line, because the boundary check ran on the transition in both directions. A line crossing is a single event, but the code detected it twice - once entering, once leaving. The off-by-one was perfectly consistent, which made it look like a constant and masked it as a real offset.",
         "Fixed by incrementing the section only on entry, and adding a test that drives the full lap and asserts the counter ends exactly at the section count."),
        ("Task base double-schedules a callback",
         ["$ python3 {file}",
          "callback ran twice per tick",
          "motor command overwritten"],
         "Every control tick produced two motor commands, the second overwriting the first. The motion was erratic because half the commands were stale by one tick.",
         "register_task was called twice for the same task ID in main - once by the module's own registration and once by the application wiring. The scheduler had no duplicate detection, so it added the callback twice. The scheduler trusted its caller; the caller did not check whether the task was already registered.",
         "Fixed by guarding register_task with a task-ID set that rejects duplicates, and logging a warning when a duplicate registration is attempted."),
        ("Log severity mapping is wrong",
         ["$ python3 {file}",
          "ERROR logged as INFO",
          "failures hidden in the console"],
         "Critical failures appeared in the log with the INFO level, so nobody noticed them in the morning's flood of messages. The logging was lying about importance.",
         "The severity enum in log_severity.py and the level table in the logger used different orderings, so the numeric codes mapped to the wrong levels. The logger wrote what it was told - the mapping was corrupted upstream. Two files defining the same concept independently is a maintenance trap: they will drift until someone notices.",
         "Fixed by defining the severity enum in the logger module itself and importing it everywhere, so only one source of truth exists."),
    ],
    9: [
        ("Lint failure in CI on unused import",
         ["$ python3 {file}",
          "flake8: F401 'sys' imported but unused",
          "CI job failed in 8s"],
         "The CI pipeline went red 8 seconds after the push. The failure was a single unused import - trivial, but it blocked the whole pipeline.",
         "The final cleanup left 'import sys' after removing the code that used it. flake8's F401 rule flags any unused import, and the CI gate treated warnings as failures. A lint failure is the cheapest possible error to catch - it costs seconds - which is exactly why the gate exists: to catch before the hardware run.",
         "Fixed by removing the import, and by running flake8 locally before pushing so the CI gate never sees the mistake."),
        ("setup.cfg ignores the pi package",
         ["$ python3 {file}",
          "pytest: no tests ran",
          "test_full_pipeline skipped"],
         "The CI reported success while running zero tests. A green pipeline is only as good as the tests it actually runs.",
         "setup.cfg listed packages manually and pi.* was missing, so pytest's package discovery found no test modules and exited with code 0 - an empty success. An empty test run looks exactly like a passing run to a CI system that only checks the exit code. The configuration and the codebase had diverged when the pi/ tree was reorganized.",
         "Fixed by switching to packages = find: so discovery is automatic, and adding a CI assertion that the test count is greater than zero."),
        ("LED pin conflict with the camera",
         ["$ python3 {file}",
          "led: 0 0 0  (camera init fails)",
          "camera and LED share a pin"],
         "The status LED was dead and the camera failed to initialize - two unrelated-looking failures that shared one cause.",
         "The LED was wired to the camera's enable pin, so driving the LED pulled the camera's enable line low. Each subsystem's config named the pin differently ('led_gpio' vs 'camera_enable'), so the conflict was invisible in the config review. The two features shared a physical resource that no single file owned.",
         "Fixed by moving the LED to a spare GPIO and adding a pin-conflict check at boot that rejects two peripherals claiming the same GPIO."),
        ("Surprise rule YAML has a duplicate key",
         ["$ python3 {file}",
          "yaml.constructor.DuplicateKeyError",
          "config load aborts"],
         "The robot failed to boot on race morning because the rules file had the same key twice. A merge conflict had duplicated a line and no one noticed.",
         "YAML strictly forbids duplicate keys, and the parser raises DuplicateKeyError - the loader correctly refused to guess which value wins. The duplicate came from a bad merge that produced two pillar_logic entries. YAML's strictness here is a feature: silently picking one of two conflicting values would be worse.",
         "Fixed by removing the duplicate, and adding a pre-merge check that parses every YAML file and rejects duplicates in CI."),
        ("Test flaky on the first run of the day",
         ["$ python3 {file}",
          "FAILED test_full_pipeline - passed 5 minutes later",
          "timing-dependent assertion"],
         "The full-pipeline test failed on the first run of the morning and passed every run after. A cold Pi is a different computer than a warm one.",
         "The test asserted that the pipeline reaches 100Hz within 2 seconds of start. A cold Pi takes longer to warm up its clocks and caches, so the first run of the day missed the deadline. Timing assertions embed an assumption about the machine state, and machine state varies with temperature and uptime.",
         "Fixed by relaxing the assertion to a 20% margin and measuring the warm-up time over a week of first runs to set a realistic bound."),
    ],
}

BIG = {
    6: [
        ("Pi SSH terminal",
         "Steering oscillates at 5Hz on the straight",
         ["$ python3 {file}",
          "steer: +5 -5 +5 -5 deg at 5Hz",
          "overshoot visible in the video"],
         "The robot wobbled down the straight at 5Hz - a visible, rhythmic steering oscillation. On the bench the servo moved perfectly; on the floor it wagged.",
         "The servo PID gains were tuned with the wheels in the air, where there is no lateral force. On the floor the tire forces and frame compliance add dynamics that the bench never exercised, and the gains that were stable on the bench were marginal on the floor. A control loop is only as good as the model it was tuned against; tuning against the wrong plant guarantees this result.",
         ["Recorded the oscillation and measured its frequency",
          "Tested the same gains with the wheels on the floor vs in the air",
          "Re-tuned with the robot on the floor using the servo_step_test"],
         "Fixed by re-tuning the servo PID with the robot on the floor, and by making the tuning procedure run on the actual competition surface."),
        ("Pi SSH terminal",
         "Integral windup launches the robot at the start",
         ["$ python3 {file}",
          "integral: 0 -> 3.8 during stall",
          "robot jumps forward 30cm"],
         "The robot jumped 30cm forward the moment it was released at the start line. The controller had been accumulating error during the stall and released it all at once.",
         "While the robot was held at the start, the position error was large and constant, and the integrator summed it until the output hit the limit. The moment the hold released, the saturated output was applied instantly - a launch, not a start. Windup storage is invisible until the constraint disappears, which is why it always surfaces at the worst moment.",
         ["Logged the integral term during the stall - it grew linearly",
          "Confirmed the jump magnitude matched the stored integral",
          "Added integral clamping and a pre-start integral reset"],
         "Fixed by clamping the integral to the output limits and resetting it when the robot is in the hold state, so the launch is a ramp, not a step."),
        ("Pi SSH terminal",
         "Global planner returns a path through the pillar",
         ["$ python3 {file}",
          "path waypoint 3: inside the pillar",
          "collision on the replay"],
         "The global planner produced a path that ran straight through a pillar. The replay showed the collision clearly - the planner never considered the robot's width.",
         "The grid cost map marked only the obstacle's exact cells as blocked. A robot has physical width, so its center can be up to half a width away from an obstacle while the robot still collides. The planner used a point model for a 20cm-wide robot. Path planning for a real robot requires the configuration-space inflation; planning a point path through the environment is planning a point's path.",
         ["Replayed the planned path against the map - the waypoint was inside",
          "Measured the clearance at the collision - less than the robot width",
          "Inflated the obstacles by the robot radius and re-planned"],
         "Fixed by inflating all obstacles by the robot radius before running A*, and adding a clearance check on the final path."),
        ("Pi SSH terminal",
         "Velocity profile ignores the corner limit",
         ["$ python3 {file}",
          "v = 2.0 m/s into a 60-degree corner",
          "tire squeal, robot drifts"],
         "The robot entered a 60-degree corner at full speed and slid wide. The profile optimized for time with no regard for what the tires can do.",
         "The velocity profile minimized lap time subject only to acceleration limits, not to lateral acceleration. A corner has a speed limit set by physics: v_max = sqrt(mu * g * r). Ignoring the curvature limit produced a profile that is fast on paper and impossible in reality - the tires physically cannot provide the required lateral force.",
         ["Measured the actual cornering speed limit on the track",
          "Overlaid the profile's speed at the corner - it exceeded the limit",
          "Added a curvature-dependent speed cap to the profile"],
         "Fixed by adding a speed cap derived from the path curvature and the measured tire limit, applied at every point of the profile."),
        ("Pi SSH terminal",
         "Cubic spline path is jerky at waypoint 5",
         ["$ python3 {file}",
          "acceleration spike: 12 m/s^2 at wp5",
          "visible jerk in the run"],
         "At waypoint 5 the robot jerked visibly. The path was smooth to the eye - the jerk was in the timing, not the shape.",
         "The spline was parameterized by a non-arc-length parameter, so equal parameter steps cover unequal distances along the path. The velocity controller interpreted parameter speed as spatial speed, producing huge accelerations where the parameterization compressed distance. A geometrically smooth path can be dynamically jerky if the parameterization is uneven.",
         ["Plotted the path speed against distance - the spike matched wp5",
          "Checked the parameterization - it was not arc length",
          "Reparameterized by arc length and re-ran"],
         "Fixed by reparameterizing the spline with arc length so parameter speed equals spatial speed, and validating the acceleration profile in the profile_test."),
        ("Pi SSH terminal",
         "Feedforward causes overshoot in sharp turns",
         ["$ python3 {file}",
          "ff: +0.8 -> overshoot 8 degrees",
          "corrective jerk after each corner"],
         "After every sharp corner the robot overshot the heading by 8 degrees and then corrected with a jerk. Gentle corners were fine - only the sharp ones overshot.",
         "The feedforward gain was tuned for the average curve and over-applied on sharp ones. The steering response is nonlinear: at large angles the servo linkage has different leverage, so a feedforward command calibrated for 30 degrees is too strong at 90. A single constant gain cannot fit a nonlinear plant across the whole operating range.",
         ["Measured the overshoot against corner sharpness - it scaled with angle",
          "Plotted the steer response vs command - nonlinear above 45 degrees",
          "Scaled the feedforward with the corner curvature"],
         "Fixed by scaling the feedforward with the path curvature, and verifying with the corner_test that the overshoot stays under 2 degrees."),
        ("Pi SSH terminal",
         "Anti-windup test fails with 30% overshoot",
         ["$ python3 {file}",
          "overshoot: 30% (target <10%)",
          "anti-windup not active"],
         "The windup test measured 30% overshoot - three times the target. The anti-windup code existed, was enabled, and did nothing.",
         "The saturation check inside the anti-windup compared the output against the wrong limits - the controller's nominal range instead of the physical PWM limits. The controller output could never exceed its nominal range, so the saturation detector never triggered, so the anti-windup was permanently inactive. The feature was dead code with its documentation claiming otherwise.",
         ["Read the windup_test output - the saturation flag never fired",
          "Compared the check limits with the real PWM limits - they differed",
          "Fixed the limits and re-ran - overshoot dropped to 4%"],
         "Fixed by comparing against the physical PWM limits in the saturation check, and adding a test assertion that the anti-windup flag actually activates during a stall."),
        ("Pi SSH terminal",
         "Obstacle avoidance deadlocks in a U-shaped trap",
         ["$ python3 {file}",
          "avoid: stuck 12s at the same spot",
          "no escape direction found"],
         "The robot stood inside a U-shaped arrangement for 12 seconds, unable to leave. Every direction it evaluated was blocked - by its own previous decisions.",
         "Local avoidance is greedy: it always chooses the best direction now. Inside a U-shape every local direction leads back inside, so the robot oscillates between two bad options forever. Without memory of where it has been, the planner cannot know it is looping. The U-shape is the classic deadlock of purely local planning.",
         ["Logged the chosen direction over time - it alternated between two",
          "Verified a memory of visited positions breaks the loop",
          "Added a heading memory that penalizes recently visited directions"],
         "Fixed by adding a small heading memory that penalizes directions tried in the last 3 seconds, forcing the planner to commit to one escape direction."),
    ],
    7: [
        ("Pi SSH terminal",
         "State machine enters PARK during lap 2",
         ["$ python3 {file}",
          "state: PARK (lap 2 of 3)",
          "lap counter said 3/3"],
         "The robot parked after lap 2 of 3 because the lap counter believed the race was over. The count was wrong - the state machine trusted it.",
         "A bump at the line made the lap counter double-count, and the race strategy terminates when laps reach 3. The state machine faithfully executed its instructions; the instructions were based on corrupted data. Two subsystems were coupled through a counter with no validation, so an error in one silently propagated to the other.",
         ["Replayed the bump - it produced two lap events",
          "Confirmed the state machine acted on the wrong count",
          "Fixed the counter with edge detection, then verified the full race"],
         "Fixed by requiring a full line crossing with cleared-edge detection to count a lap, and adding a sanity check that rejects lap counts closer than 3 seconds apart."),
        ("Pi SSH terminal",
         "Start line missed because the camera was still warming",
         ["$ python3 {file}",
          "start: never detected (60s)",
          "camera ready at t=8s, start at t=3s"],
         "The robot missed the start line entirely because the camera was not ready when the line appeared. The detector ran blind and nobody knew.",
         "The start detector subscribed to camera frames the moment the pipeline started, but the camera needed 8 seconds to produce usable frames. The start line was crossed at t=3s - before the first good frame. The detector reported 'no line' for frames that did not exist; there was no readiness signal between the camera and the detector.",
         ["Timed the camera readiness - 8s, longer than the approach",
          "Logged the frames the detector actually saw - zero valid ones",
          "Added a camera-ready signal gating the start detection"],
         "Fixed by delaying the start detection until the camera reports ready, and logging 'camera warming' during the wait so the state is visible."),
        ("Pi SSH terminal",
         "Direction logic fails after a 180-degree obstacle",
         ["$ python3 {file}",
          "direction: forward (robot now reversed)",
          "pillars tracked on the wrong side"],
         "After a 180-degree avoidance maneuver the robot tracked pillars on the wrong side. The direction state still said forward while the robot faced backward.",
         "The 180-degree maneuver was implemented in the obstacle strategy as a series of motor commands, bypassing the normal direction-tracking code path. The direction module had no knowledge of the maneuver, so its state was stale. When the logic is bypassed, the state that depends on it silently rots.",
         ["Replayed the maneuver - the flag never changed",
          "Found the bypass in the obstacle strategy code",
          "Routed the maneuver through the direction module"],
         "Fixed by implementing the 180-degree maneuver inside the direction module, and adding an assertion that the direction flag matches the IMU heading within 30 degrees."),
        ("Pi SSH terminal",
         "Parking state overshoots and hits the wall",
         ["$ python3 {file}",
          "park: robot 12cm past the line",
          "wall bump at 0.4m/s"],
         "The parking maneuver drove 12cm past the line and bumped the wall at 0.4 m/s. The park logic was correct - the speed was not.",
         "The park state reused the race approach speed of 0.4 m/s. At that speed the robot travels 40cm in one second, and the parking correction latency is several hundred milliseconds - the stopping distance alone exceeded the zone tolerance. Parking is a precision task executed with race parameters.",
         ["Measured the stopping distance at the park speed - over the tolerance",
          "Checked the park approach speed - it was the race value",
          "Capped the park speed and re-ran the park_sm test"],
         "Fixed by capping the park approach speed at 0.15 m/s and adding a distance budget check that aborts the approach if the remaining distance is insufficient to stop."),
        ("Pi SSH terminal",
         "Race strategy bets everything on the wrong lane",
         ["$ python3 {file}",
          "lane chosen: outer (inner clear)",
          "lost 1.5s over the race"],
         "The race strategy committed to the outer lane for all three laps while the inner lane was clear from lap 2 on. A wrong early decision was locked in.",
         "The lane decision was made once before lap 1 from a single observation. Track conditions change during a race - an obstacle may move or a line may clear - and a one-time decision cannot adapt. Committing to a fixed plan in a dynamic environment turns every change into a penalty.",
         ["Replayed the race - the inner lane was clear from lap 2",
          "Checked when the strategy re-evaluates - only at race start",
          "Made the lane score re-evaluate at every lap boundary"],
         "Fixed by recomputing the lane score at every lap boundary, and by adding a mid-race override when the live obstacle state changes by more than a threshold."),
        ("Pi SSH terminal",
         "Checkpoint gate triggers twice per crossing",
         ["$ python3 {file}",
          "checkpoint 3: 2 events",
          "bonus counted twice"],
         "Every checkpoint produced two events instead of one, doubling the bonus count. The scoring was quietly wrong by a factor of two.",
         "The gate trigger fired on both the leading edge and the trailing edge of the crossing - the code treated entering and leaving the gate as two separate events. A gate is a region, and the trigger logic did not define which transition counts. Without an explicit edge definition, every boundary transition is an event.",
         ["Counted the events per crossing - exactly two, every time",
          "Traced the trigger to both boundary transitions",
          "Added a cleared-edge requirement and re-ran"],
         "Fixed by triggering only on entry and requiring the gate to be fully cleared before the next trigger, verified in the checkpoint test."),
        ("Pi SSH terminal",
         "Reverse logic stalls at a wall",
         ["$ python3 {file}",
          "reverse: 0.2s, forward: 0.2s, loop",
          "robot stuck for 9s"],
         "The robot shuffled against a wall for nine seconds, reversing 0.2s and advancing 0.2s forever. Both motions worked; the combination was useless.",
         "The reverse duration was a fixed 0.2 seconds, shorter than the time needed to clear the wall overlap. Each forward attempt re-engaged the wall by more than the reverse had cleared, so the net progress per cycle was negative. A fixed parameter can only be correct for one geometry; the wall overlap varies.",
         ["Measured the wall overlap vs the reverse distance - negative net",
          "Timed how long a reverse needed to clear the overlap",
          "Made the reverse distance proportional to the overlap"],
         "Fixed by making the reverse distance proportional to the measured obstacle overlap, and adding a minimum total reverse time to the strategy."),
        ("Pi SSH terminal",
         "Lap counter breaks when the robot stops on the line",
         ["$ python3 {file}",
          "laps: 2 (stopped exactly on the line)",
          "race cannot finish"],
         "The robot stopped exactly on the lap line and the counter refused to advance. The robot was on the line - why did the count not register?",
         "The lap counter only counted a lap when it observed a transition from 'not on line' to 'on line'. The robot crossed the line while the counter was still resolving the previous state, so no transition was ever observed. Counting transitions instead of positions means a valid crossing can be invisible if it coincides with the state resolution.",
         ["Reproduced by stopping exactly on the line",
          "Checked the counter logic - it demanded a transition",
          "Added a position-based check that accepts a stationary crossing"],
         "Fixed by also counting a lap when the robot is detected on the line in the correct direction while the previous lap is already confirmed."),
    ],
    8: [
        ("Pi SSH terminal",
         "Scheduler deadlocks when a task raises",
         ["$ python3 {file}",
          "scheduler: task 'vision' raised, never resumed",
          "all other tasks stop"],
         "One exception in the vision task froze the entire robot - every other task stopped scheduling. The failure was in the exception path, not the task.",
         "The scheduler loop had no exception boundary around its task invocations. When vision raised, the exception propagated out of the loop, and the asyncio gather never continued, so no task ever ran again. A system of cooperating tasks is only as robust as its weakest task unless the scheduler contains each one.",
         ["Reproduced with a forced exception in a test task",
          "Confirmed the gather exited and nothing resumed",
          "Wrapped each task call in try/except and re-ran"],
         "Fixed by wrapping every task invocation in try/except with logging, so a failing task is isolated and the scheduler keeps running."),
        ("Pi SSH terminal",
         "Heartbeat failure cuts the motors at the start line",
         ["$ python3 {file}",
          "heartbeat: FAIL (start signal)",
          "motors disabled for 3s"],
         "At the start signal the motors were disabled for three seconds - the failsafe fired exactly when the robot needed to move. The start burst starved the heartbeat.",
         "At start, the vision and fusion tasks all wake at once and consume CPU for hundreds of milliseconds. The low-priority heartbeat thread could not run within its timeout window, so the failsafe - which is supposed to catch a dead loop - caught a merely busy one. The safety system could not tell the difference, and its design made it fire on exactly this pattern.",
         ["Logged CPU usage at the start burst - the heartbeat starved",
          "Confirmed the failsafe fired while the loop was healthy",
          "Prioritized the heartbeat and widened the timeout"],
         "Fixed by boosting the heartbeat to a high-priority thread with a 2s timeout, so a busy-but-healthy system never trips the failsafe."),
        ("Pi SSH terminal",
         "Surprise rule change requires a reboot",
         ["$ python3 {file}",
          "rule changed in config: not applied",
          "robot keeps the old strategy"],
         "The rules were changed before a round, but the robot kept playing the old strategy. The config file was correct - the robot never read it again.",
         "surprise_config loaded the rules once at boot and cached them in memory. Every later read returned the cached copy, so an on-the-spot rule change could only take effect after a reboot - an impossible requirement between rounds. Configuration that is read once is not configuration, it is a build-time constant.",
         ["Changed a rule and observed no effect - cached config",
          "Checked the load path - it ran only at boot",
          "Added a reload at each round start"],
         "Fixed by re-reading the rules file at every round start, with a file-hash check that logs whether the active rules changed since boot."),
        ("Pi SSH terminal",
         "Track map mismatch after the first lap",
         ["$ python3 {file}",
          "map section 6/8 but lap counter says 1",
          "strategy uses the wrong corner data"],
         "After one lap the track map believed the robot was in section 6 while the lap counter said lap 1. The strategy prepared for the wrong corner every lap after the first.",
         "The track map and the lap counter each maintained their own position state and updated it at different points in the pipeline. Their states were never compared, so they drifted apart silently. Two sources of truth for the same quantity will always diverge; the only question is when they are noticed.",
         ["Logged both states after lap 1 - they disagreed",
          "Traced the update points - different pipeline stages",
          "Merged them into a single shared lap state"],
         "Fixed by sharing one lap-state object between the map and the counter, with a consistency assertion that fails loudly if they ever disagree."),
        ("Pi SSH terminal",
         "Health monitor kills the camera on a cold start",
         ["$ python3 {file}",
          "camera: FAIL -> restart -> FAIL (3x)",
          "camera was fine after 60s"],
         "The health monitor restarted the camera three times at boot, then gave up - while the camera was simply slow to start in the cold. The monitor caused the failure it was watching for.",
         "The camera produces no frames for the first several seconds on a cold boot. The health monitor interpreted the silence as a failure and issued a restart, and each restart reset the same cold-start condition. The monitor's retry loop amplified the boot transient into a permanent failure - the fix was the opposite of the restart it kept performing.",
         ["Noticed the camera recovered when left alone",
          "Timed the cold-start delay - it exceeded the health timeout",
          "Added a grace period before the first camera check"],
         "Fixed by waiting 10 seconds before the first camera health check, and by backing off restarts exponentially instead of restarting instantly."),
        ("Pi SSH terminal",
         "ESP32 flash with the wrong partition table",
         ["$ python3 {file}",
          "esptool: data does not match the partition table",
          "ESP32 boot loops"],
         "After flashing, the ESP32 boot-looped. The flash succeeded - the app was written to a partition the partition table did not define.",
         "The application partition had grown past the size declared in the partition table, or the table itself was for a different flash layout. The chip boots into the app region from the table; if the table does not describe the flashed layout, the bootloader cannot find the app and resets. The build and the flash layout were not validated against each other.",
         ["Read the boot logs - the partition entry was missing",
          "Compared the partition table with the app size",
          "Reflashed with the standard 4MB table"],
         "Fixed by pinning the partition table in the project config, and adding a CI check that fails if the compiled app exceeds its partition."),
        ("Pi SSH terminal",
         "OOM killer kills the perception process",
         ["$ python3 {file}",
          "Out of memory: Killed process 1234 (vision)",
          "perception dead, robot runs blind"],
         "The perception process was killed by the kernel's OOM killer mid-run. The robot kept driving - blind, because nobody noticed the process was gone.",
         "The vision frame queue had no size limit, so under load it buffered frames without bound and consumed the Pi's RAM. When memory ran out, the kernel's OOM killer chose the largest process - the vision process. The queue was a convenience that became a memory leak the moment consumers lagged producers.",
         ["Checked dmesg for the OOM kill - the vision process was the target",
          "Measured the RSS growth - it grew linearly with queue length",
          "Capped the queue and re-ran under load"],
         "Fixed by capping the frame queue at 4 frames with drop-oldest, and adding a memory watch that logs the RSS of each process to the health monitor."),
        ("Pi SSH terminal",
         "Log severity floods the disk on a bad day",
         ["$ python3 {file}",
          "/var/log: 4.2GB of WARNING lines",
          "SD card 99% full"],
         "One bad day of testing filled the SD card with 4.2GB of warning lines. The robot kept working - until the card was full and everything stopped.",
         "A rate-limit regression let the error logger write at full rate, and the log had no rotation on the embedded system. Logging is storage I/O; unbounded logging is an unbounded disk consumption. The rate limiter that had fixed the console spam did not cover the file writer.",
         ["Found the 4.2GB log and its growth rate",
          "Traced the spam to a rate-limiter regression",
          "Added rotation and a disk watermark alert"],
         "Fixed by fixing the rate limiter for the file writer and adding log rotation with a 50MB cap, plus a warning when the disk crosses 90%."),
    ],
    9: [
        ("Pi SSH terminal",
         "Full pipeline crashes 2 seconds after the start",
         ["$ python3 main.py",
          "Traceback (most recent call last):",
          "  File \"main.py\", line 88, in <module>",
          "    scheduler.start()",
          "  File \"pi/system/scheduler.py\", line 31",
          "    await asyncio.gather(*tasks)",
          "TypeError: 'Task' object is not callable"],
         "The final integrated system crashed two seconds after launch - after all subsystems had started successfully. The crash was in the scheduler, the last piece to start.",
         "The scheduler defined a class named Task, shadowing asyncio.Task inside the module. asyncio.gather expects coroutine objects or Tasks; it received the module's own Task class instance, which is not awaitable, raising TypeError. The name collision was invisible until the exact code path that combined both symbols executed - which only happens at the very end of startup.",
         ["Read the traceback - the scheduler line and the class name matched",
          "Checked asyncio.gather's requirements against the argument",
          "Renamed the internal class and verified the whole startup"],
         "Fixed by renaming the internal class to ScheduledTask, and adding a smoke test that runs the full startup sequence before every race."),
        ("Pi SSH terminal",
         "Camera frozen at the race morning start",
         ["$ python3 main.py",
          "frame: identical for 40s",
          "camera driver: no error, no frame"],
         "On race morning the camera output a single frozen frame for 40 seconds. No error, no exception - just a frame that never changed, while the robot drove blind.",
         "The camera read call had no timeout, so when the sensor stalled (a known cold-start quirk of the camera module), the driver blocked forever inside read(). Blocking reads fail silently by design: the code waits, nothing happens, no signal is raised. The pipeline kept consuming the last frame, so the system looked alive while being blind.",
         ["Confirmed the frame was a single frame repeated, not a new capture",
          "Checked the driver - the read had no timeout",
          "Added a timeout that raises after 2s of no frame"],
         "Fixed by adding a 2-second read timeout that triggers a camera restart, and logging 'camera frozen' when a restart occurs."),
        ("ESP32 serial monitor",
         "ESP32 watchdog resets during the final run",
         ["E (89430) task_wdt: Task watchdog got triggered",
          "task: motor_ctrl did not reset the watchdog",
          "Rebooting... (loop)"],
         "The ESP32 rebooted in the middle of the final run - 89 seconds in, the motor task had not fed its watchdog. The loop restarted the robot at full speed.",
         "The motor task blocked on a UART write with no timeout: the Pi stopped reading (its own CPU was saturated), the ESP32's TX buffer filled, and the write waited forever. A blocked write means no watchdog feed, and the hardware watchdog correctly reset the system. Two independent saturation problems met in one blocking call.",
         ["Decoded the watchdog message - the motor task was the victim",
          "Logged the UART write - it blocked when the Pi stopped reading",
          "Made the write non-blocking with a timeout"],
         "Fixed by setting the UART write to non-blocking with a 10ms timeout, and feeding the watchdog before every write so a stalled link cannot stall the loop."),
        ("Pi SSH terminal",
         "Serial permission denied at autostart",
         ["$ sudo systemctl start wro-robot",
          "serial.serialutil.SerialException: Permission denied",
          "autostart failed, manual run works"],
         "The robot would not start through the autostart service, while the same command worked manually. The only difference was who ran it.",
         "The systemd service ran as the root user by default, and the serial device was owned by the dialout group. Root bypasses file permissions - the real issue was the service ran as a user without dialout access after hardening. Manual runs worked because the shell user was in the dialout group; the service was not.",
         ["Ran the service manually - it failed the same way",
          "Checked the service user and the device permissions",
          "Added the service user to the dialout group"],
         "Fixed by adding the service user to the dialout group and verifying autostart after a full reboot, not just a service restart."),
        ("ESP32 serial monitor",
         "Core dump triggered: store data at 0x3ffb0e10",
         ["Core 0 panic'ed (StoreProhibited)",
          "store data at 0x3ffb0e10, pc 0x400df220",
          "Backtrace: 0x400df220:0x3ffb1f30 scheduler_tick"],
         "The ESP32 crashed with a StoreProhibited panic - a write to protected memory. The backtrace pointed at the scheduler, of all places.",
         "The scheduler task wrote to a task context that had been freed: a task was deleted, its memory returned to the heap, and the scheduler still held a pointer to it. A use-after-free is a memory bug that appears at the moment the allocator reuses the freed block - which is why it only crashed under specific timing.",
         ["Decoded the panic - StoreProhibited at the scheduler tick",
          "Traced the pointer - it referenced a deleted task",
          "Deferred task deletion to the idle hook"],
         "Fixed by deferring task deletion to the idle hook so the scheduler never touches freed contexts, and adding a task-count assertion at every delete."),
        ("Pi SSH terminal",
         "Race day: SD card corrupt after the power cut",
         ["$ journalctl",
          "ext4-fs error (device mmcblk0p2)",
          "Remounting filesystem read-only",
          "python3: can't open file 'main.py'"],
         "On race day the SD card was corrupted by the power cut during the previous night's calibration. The filesystem remounted read-only and the robot could not even start Python.",
         "The Pi was powered off without a clean shutdown, and the ext4 journal could not replay, leaving the filesystem in an inconsistent state. ext4 responded by remounting read-only to protect the data. A robot that is powered off by pulling the battery is a robot that will eventually lose its filesystem - the shutdown was an operational habit, and it became a race-day failure.",
         ["Mounted the card on a PC and ran fsck",
          "Recovered the code from the backup image",
          "Converted the root filesystem to read-only with an overlay for logs"],
         "Fixed by switching to a read-only rootfs with a RAM-backed log overlay, so power cuts can never corrupt the boot filesystem again."),
        ("Pi SSH terminal",
         "Pillar detector false positive on the scoreboard",
         ["$ python3 main.py",
          "pillar: RED at (200,150) x 40 frames",
          "scoreboard is not a pillar"],
         "During the final round the detector locked onto the electronic scoreboard for 40 frames and the robot steered toward the wrong target. The scoreboard is exactly the size and color of a pillar.",
         "The red electronic scoreboard matched every gate in the pillar filter: color, size, aspect ratio. The filter had no context - it could not know that a red rectangle at that position and distance was a scoreboard. The scoreboard was the perfect counterfeit: it satisfied every feature the detector checked, because the detector checked only features the pillar has.",
         ["Replayed the round - the 40-frame lock was on the scoreboard",
          "Checked the detection - it passed all gates",
          "Masked the scoreboard region and re-ran the round"],
         "Fixed by masking the top 20% of the frame where the scoreboard sits, and adding a position-vs-distance consistency check against the ToF."),
        ("ESP32 serial monitor",
         "UART command echo storm between the two boards",
         ["$ idf.py monitor",
          "echo: MOTOR left=0.5 right=0.5",
          "echo: MOTOR left=0.5 right=0.5",
          "echo: ... 400 lines/sec"],
         "The ESP32 console flooded with echo lines - its own commands, coming back to it. The two boards were talking to each other in a loop at 400 lines per second.",
         "The RX and TX lines were swapped between the boards: each board's TX fed the other's TX, so every command written by the Pi arrived back at the Pi, which echoed it as a response, which the ESP32 interpreted as a new command. With no checksum, both boards accepted the garbage as valid traffic. A crossed wire plus a trusting protocol equals a feedback loop.",
         ["Recognized the pattern - each board heard its own commands",
          "Swapped the RX/TX lines - the storm stopped",
          "Enabled the protocol checksum so garbage is rejected"],
         "Fixed by swapping the two wires and enabling the checksum in the protocol, so a wiring error now produces a clear checksum error instead of an echo storm."),
    ],
}
