"""Error template data for the WRO error catalog - themes 1..5.

Every template is a tuple:
  SMALL: (error, [terminal lines], what-happened, why-root-cause, fix)
  BIG:   (terminal, error, [terminal lines], what-happened,
          why-root-cause, [investigation steps], fix)
"""

SMALL = {
    1: [
        ("ModuleNotFoundError: No module named 'sensors'",
         ["$ python3 {file}",
          "Traceback (most recent call last):",
          "  File \"{file}\", line 6, in <module>",
          "    from sensors.camera import PiCamera",
          "ModuleNotFoundError: No module named 'sensors'"],
         "The very first morning run of v1.x died at the first import, before a single line of robot code could execute. The whole skeleton was there, but Python refused to see it.",
         "Python resolves packages through sys.path, and sys.path[0] is the directory of the script being run, not the current working directory. The sensors package lived under pi/, so launching from the repo root made it invisible. ModuleNotFoundError is raised at import time, which means everything after the import line is unreachable - no logs, no GPIO init, nothing.",
         "Fixed by running the script from inside pi/, and later made permanent with sys.path.insert(0, os.path.dirname(__file__)) so the package resolves no matter where the script is launched from."),
        ("ImportError: cannot import name 'PiCamera'",
         ["$ python3 {file}",
          "Traceback (most recent call last):",
          "  File \"{file}\", line 3, in <module>",
          "    from picamera2 import PiCamera",
          "ImportError: cannot import name 'PiCamera' from 'picamera2'"],
         "The first camera test failed at import. The library was installed, so the surprise was that the symbol itself was missing.",
         "picamera2 exports the class Picamera2 with a capital P. Python names are case-sensitive, and unlike C there is no link-time check - the failure only appears when the module is actually imported on the Pi. It never shows on the PC because the package does not exist there at all, which is exactly why this slipped past the laptop tests.",
         "Fixed by using the exact class name Picamera2 and adding a startup import check so the mistake fails loudly and early instead of silently."),
        ("IndentationError: unexpected indent",
         ["$ python3 {file}",
          "  File \"{file}\", line 12",
          "    print('i2c ok')",
          "IndentationError: unexpected indent"],
         "The morning's edits crashed the script before it even started. A block that looked right in the editor was illegal to the interpreter.",
         "The file mixed tab characters with spaces. Python 3 forbids mixing them for indentation because they are ambiguous - one tab can be 4, 8 or 12 columns depending on the editor. The parser rejects the file during compilation, so no code runs at all; the error appears the instant the script is launched.",
         "Fixed by reformatting the block with spaces only, then setting the editor to convert tabs to 4 spaces so it can never come back."),
        ("TypeError: unsupported operand type(s) for +: 'int' and 'str'",
         ["$ python3 {file}",
          "  File \"{file}\", line 18, in <module>",
          "    dev = bus.read_byte_data(addr, reg) + 'x'",
          "TypeError: unsupported operand type(s) for +: 'int' and 'str'"],
         "The I2C scan report crashed halfway through building its output line. It had worked yesterday on the happy path, so the bug only appeared on a specific address.",
         "read_byte_data returns an int, and the code appended the string 'x' to it. Python is dynamically typed, so the mismatch is only detected at runtime - the line only executed for addresses that returned a value, which is why the earlier test addresses passed silently. This is a classic type-contract bug that static analyzers catch immediately.",
         "Fixed with str() wrapping and a review rule: every format that mixes types goes through f-strings, where the conversion is explicit."),
        ("NameError: name 'smbus' is not defined",
         ["$ python3 {file}",
          "  File \"{file}\", line 9, in <module>",
          "    bus = smbus.SMBus(1)",
          "NameError: name 'smbus' is not defined"],
         "The I2C bus scan died at the first bus access. The import line at the top of the file was there, so the name should have existed.",
         "The import statement import smbus2 was present, but the code referenced smbus. The alias was never created because the import was never written - the file used the raw package name in one place and the alias in another. NameError surfaces lazily at the first use of the name, not at import time, so the file parsed fine and only exploded mid-run.",
         "Fixed by importing smbus2 as smbus and running a quick grep for every usage to confirm no other raw references remained."),
        ("FileNotFoundError: [Errno 2] No such file or directory: 'config.json'",
         ["$ python3 {file}",
          "  File \"{file}\", line 22, in <module>",
          "    with open('config.json') as f:",
          "FileNotFoundError: [Errno 2] No such file or directory: 'config.json'"],
         "The script died while reading its configuration. It worked in the repository, so the missing file only appeared once the code was deployed to the robot.",
         "The config file was never copied to the Pi - only the code folder was synced. Worse, the path was relative, so the file location depended on the working directory at launch; systemd and cron would look in entirely different places. The error is raised by the open() syscall when the kernel returns ENOENT, and nothing in the code anticipated it.",
         "Fixed by scp'ing the config, switching to an absolute path built from the script location, and adding an explicit existence check with a clear message at boot."),
        ("SyntaxError: invalid syntax",
         ["$ python3 {file}",
          "  File \"{file}\", line 30",
          "    if addr == 0x68:",
          "SyntaxError: invalid syntax"],
         "The script died instantly with a parse error on a line that looked perfectly fine in the editor.",
         "The line was missing its trailing colon - the editor's syntax highlighting had not refreshed, so the mistake was invisible. SyntaxError is raised during the compile phase before any bytecode is produced, which is why the program produced zero output; the grammar validator rejected the token stream before execution began.",
         "Fixed by adding the colon, and the editor was switched to save-on-format so parse errors cannot hide again."),
        ("ValueError: invalid literal for int() with base 10",
         ["$ python3 {file}",
          "  File \"{file}\", line 41, in <module>",
          "    speed = int(input('speed: '))",
          "ValueError: invalid literal for int() with base 10: 'fast'"],
         "The manual calibration test crashed because the person at the keyboard typed a word where a number belonged.",
         "input() always returns a string, and int() is strict - any non-numeric character raises ValueError. The function had no validation layer, so garbage input took down the whole test harness instead of being rejected politely. This is a human-interface error, not a hardware one, but it still cost a morning because the crash aborted the calibration run.",
         "Fixed by wrapping input in try/except with a retry loop and validating the range before accepting the speed value."),
    ],
    2: [
        ("Duty value out of range 0-1023",
         ["$ idf.py monitor",
          "E (312) ledc: duty out of range!",
          "E (312) ledc: duty=4095, max=1023",
          "abort() was called at PC 0x42012345"],
         "The very first motor spin aborted the ESP32. The duty value was huge, and the LEDC driver refused it immediately.",
         "The PWM timer was configured with 10-bit resolution (max 1023) but the speed calculation produced 14-bit values up to 4095. The mismatch came from two headers defining the resolution differently - pwm_config.h said 10 bits while the speed table was written for 14. The abort() is a hard assert inside the driver, by design: an out-of-range duty would produce undefined PWM behavior, so the firmware kills itself rather than corrupt the motors.",
         "Fixed by clamping the duty in one place inside speed_control.c and asserting the resolution constant at boot, so both sides can never disagree again."),
        ("Signed char overflow in speed command",
         ["$ idf.py monitor",
          "I (401) uart: MOTOR left=200 right=-30",
          "E (402) motor: speed 200 overflows int8",
          "motor stuck at 127"],
         "The motor ran at half speed during calibration and ignored the requested value of 200. The command had clearly been received - it was printed in the log.",
         "The UART parser stored speeds in an int8_t, whose maximum is 127. The value 200 overflowed to -56, which the driver then clamped to 127. The bug was a protocol/schema mismatch: the Pi generated a text protocol with no stated range, and the ESP32 guessed the width. Signed overflow in C is undefined behavior, so in principle anything could have happened - here it produced a silently wrong motor command.",
         "Fixed by widening the parser to int16_t, adding a range check that rejects speeds outside -100..100, and documenting the protocol range in the header."),
        ("Wheels spin the wrong way after boot",
         ["$ python3 {file}",
          "forward: left=+1.0 right=+1.0",
          "result: robot drives BACKWARD"],
         "The first drive test showed a robot that drove away from its operator while the log clearly said FORWARD. Hardware did what the pins said, not what the label said.",
         "The motor channel macros were swapped relative to the physical wiring - channel A was driving the right motor and the code believed it was the left. PWM duty of +1 is just a number; the direction comes from the H-bridge enable pins, which were crossed. No software check can catch this; only a physical test with a known direction reveals it.",
         "Fixed by swapping the two channel macros, then adding a boot self-test that spins each wheel by name and asks a human to confirm the direction."),
        ("Ackermann steer angle sign is flipped in a left turn",
         ["$ python3 {file}",
          "left turn -> inner wheel angle +18deg",
          "expected inner wheel angle -18deg"],
         "The simulation produced perfect Ackermann angles, but the real robot turned the wrong way. The math was checked twice and was correct on paper.",
         "The sign convention of the Ackermann geometry disagreed with the physical servo mounting. The robot's steering linkage pushes the wheel right when the servo angle is positive, so a mathematically positive inner-wheel angle turned the robot left. The model lived in the Pi, the mechanical convention lived in the chassis, and nothing connected the two until a physical turn test.",
         "Fixed by negating the angle at the servo write boundary and adding a physical direction test to the turn_test script, with a comment documenting the mechanical convention."),
        ("Encoder tick count stays 0",
         ["$ python3 {file}",
          "ticks: 0, 0, 0, 0",
          "speed: 0.00 m/s (wheel never moved)"],
         "The wheel spun visibly, but the odometry reported zero ticks. The speed readout insisted the wheel was stationary while it was turning at full speed.",
         "During rewiring, the encoder's two signal wires were swapped with the motor's power wires. The encoder needs power and a clean signal; with power and signal crossed, the interrupt pin floated and never changed state. The encoder ISR never fired, so the tick counter stayed at zero - a silent failure because no error was ever raised, just wrong data.",
         "Fixed by matching the connector pinout against the datasheet, then adding a sanity check that raises a warning when the wheel spins with zero ticks."),
        ("PID D-term spikes to NaN after a bump",
         ["$ python3 {file}",
          "error=0.002 dterm=nan",
          "pid output = nan",
          "motor ramps to full speed"],
         "The robot surged to full speed for a moment after rolling over a bump, then recovered. The D term was the only thing that looked strange.",
         "The derivative was computed as (error - last_error) / dt with dt=0. A bump caused two identical encoder samples with a zero time delta, dividing by zero. Python returns NaN for 0/0, and NaN propagates through every subsequent arithmetic - the PID output became NaN, which compared false against all limits, so the safety clamp never triggered.",
         "Fixed by adding a low-pass filter on the D term and replacing the division with a guarded version that keeps the previous value when dt is below a threshold."),
        ("Gyro reads 250 deg/s idle",
         ["$ python3 {file}",
          "gyro: 248.3 deg/s  (expected ~0)",
          "imu status: SUSPECT"],
         "The robot sat perfectly still on the bench while the gyro claimed it was spinning at 248 degrees per second - a quarter of a full rotation per second, standing still.",
         "The MPU6050 was running at its default full-scale range with factory offsets. Factory gyro offsets are rarely zero, and the raw value is scaled by the full-scale constant - with the 250 dps range selected the bias of the sensor element maps to tens of degrees per second. Calibration is not a refinement, it is a prerequisite: without the bias subtraction the reading is meaningless.",
         "Fixed by writing the calibrated offset registers during init and re-running the v3.1 calibration whenever the board or mounting changes."),
        ("Keyboard control ignores held keys",
         ["$ python3 {file}",
          "key 'w' not detected during 'a' hold",
          "robot turns but never speeds up"],
         "Manual driving felt broken: holding 'w' while turning did nothing, even though the key worked alone. The robot turned, but never accelerated.",
         "The keyboard handler used a blocking read, so while one key was held, the handler waited for that key to be released before reading the next. The terminal delivers one event at a time; a blocking getch() cannot represent two simultaneous keys. This is a fundamental limitation of line-buffered terminal input, not a bug in the key table.",
         "Fixed by switching to raw mode with a non-blocking poll and maintaining a key-state table, which records every pressed key and merges them each control tick."),
    ],
    3: [
        ("MPU6050 WHO_AM_I mismatch 0x00",
         ["$ python3 {file}",
          "WHO_AM_I = 0x00 (expected 0x68)",
          "IMU not found on bus"],
         "The IMU log script reported the sensor was absent even though it was wired and powered. The address check failed on the very first register read.",
         "The MPU6050 answers at 0x68 or 0x69 depending on the AD0 pin. With AD0 floating, the pin read as high at power-up and the chip moved to 0x69, while the code only probed 0x68. WHO_AM_I returning 0x00 means the device never even acknowledged - the wrong address was being addressed, so the chip stayed silent.",
         "Fixed by pulling AD0 to ground with a resistor and adding a bus scan that discovers the device address instead of assuming it."),
        ("Calibration JSON has no 'gyro_offset' key",
         ["$ python3 {file}",
          "KeyError: 'gyro_offset'",
          "  File \"{file}\", line 27, in load_calib"],
         "The IMU driver crashed at startup reading its calibration file. The file existed and looked complete - the schema was the problem.",
         "The calibration file was produced by an older calibration script that stored the fields under different names. The loader used strict key access (calib['gyro_offset']) so a renamed key raised KeyError instantly. There was no schema version in the file and no migration path, so old and new files were indistinguishable until load time.",
         "Fixed by adding a schema version field, a default fallback for missing keys, and regenerating imu_calib.json with the new format."),
        ("Complementary filter alpha out of bounds",
         ["$ python3 {file}",
          "filter_config.json: alpha=1.7",
          "pitch follows raw accel with spikes"],
         "The live pitch plot showed violent spikes as if the gyro was ignored. The filter ran, but the numbers made no physical sense.",
         "The complementary filter weights gyro integration by alpha and the accelerometer by (1 - alpha). With alpha=1.7 the accelerometer weight became -0.7, so the filter was actively amplifying accelerometer noise instead of suppressing it. A typo in filter_config.json wrote 1.7 instead of 0.7, and nothing validated the config against the [0,1] domain the math requires.",
         "Fixed by clamping alpha at load time and adding a config validator that rejects values outside [0,1] with a readable error."),
        ("Magnetometer saturates near the drive motors",
         ["$ python3 {file}",
          "mag: x=+32767 y=-32767 z=+1024",
          "heading: jumping 0..359"],
         "The heading readout became random noise whenever the throttle rose. At standstill it was fine; the moment the motors spun, the compass went mad.",
         "The QMC5883L's ADC saturated at its ±32767 output limits, which means the magnetic field at the sensor exceeded its measurement range. The motor current creates a strong magnetic field a few centimeters away, and at 2cm distance the field strength is comparable to the Earth's field the sensor is trying to measure. Saturated ADC values are not noise - they are clipped, which corrupts the heading completely.",
         "Fixed by moving the sensor 5cm from the motor wiring, adding hard-iron offset calibration, and masking the heading while the throttle exceeds a threshold."),
        ("ToF distance frozen at 0",
         ["$ python3 {file}",
          "dist: 0, 0, 0, 0, 0 mm",
          "wall state: UNKNOWN"],
         "The distance sensor returned exactly zero on every read. Not an error, not a range value - a perfect, suspicious zero every time.",
         "The VL53L0X boot sequence requires specific register writes with strict timing between them. The init code skipped a required 5ms delay, so the sensor never left its boot state and returned the default register value of 0. The sensor was not broken - it was never initialized. This is why vendor init sequences must be copied exactly, including every delay.",
         "Fixed by restoring the complete init sequence with all inter-register delays, and adding a power-on self-check that verifies a non-zero reading."),
        ("ToF range error 7 (VL53L1X) floods the log",
         ["$ python3 {file}",
          "WARNING: range status 7 (signal fail)",
          "WARNING: range status 7 (signal fail)",
          "... 600 lines/second ..."],
         "The console became a waterfall of identical warnings. Within seconds the useful log was buried under thousands of identical lines.",
         "The reflective venue tile produced a weak return echo, so the VL53L1X reported range status 7 (signal fail). The error path logged at full loop rate with no throttle - 600 lines per second is simply the loop rate. Logging is I/O, and I/O at that rate saturated the serial link and starved the control loop of CPU time.",
         "Fixed with a rate limiter that logs the error at most once per 2 seconds and counts the suppressed occurrences, mirroring the I2C fix."),
        ("Wall state flips every frame",
         ["$ python3 {file}",
          "state: LEFT WALL, RIGHT WALL, LEFT WALL, ...",
          "distance jitter +-4cm"],
         "The wall-following state changed sides every single frame, making the robot oscillate between two behaviors at 10Hz. The distance was stable within a few centimeters.",
         "The state threshold sat exactly in the middle of the sensor's noise band. A 4cm jitter crossed the threshold in both directions constantly, and the state machine had no hysteresis - no memory of the previous state to suppress rapid toggling. Threshold logic without hysteresis amplifies sensor noise into state oscillation.",
         "Fixed by adding a 6cm hysteresis band around the threshold so the state only changes when the distance clearly leaves the current side."),
        ("Camera capture returns a black frame",
         ["$ python3 {file}",
          "frame mean = 2.1 (near black)",
          "camera seems dead"],
         "The camera test produced almost entirely black frames. The sensor was alive - the log showed it was capturing - but the image was dark.",
         "The camera was still in preview mode with auto-exposure running when the first capture happened. The capture raced the exposure settling, so the frame froze before the sensor adapted to the light. A camera is not instantly ready: after start, the auto-exposure algorithm needs several frames to converge, and a read immediately after init captures the un-converged state.",
         "Fixed by forcing a 500ms settle delay after camera start and discarding the first three frames before using any image."),
    ],
    4: [
        ("HSV lower bound bigger than upper bound",
         ["$ python3 {file}",
          "ValueError: lower should be smaller than upper",
          "  File \"{file}\", line 34, in detect"],
         "The red pillar detector crashed the first time it processed a real frame. The color range that worked in tests was rejected by OpenCV.",
         "Red hue wraps around the HSV cylinder: red is both 0-10 and 170-180. Writing it as one continuous range (170..10) is invalid because lower > upper, which cv2.inRange rejects with a ValueError. The wrapper range is a conceptual mistake - the hue circle has no beginning, so the mask must be built from two disjoint ranges and OR-ed together.",
         "Fixed by splitting the red range into two masks (0-10 and 170-180) and OR-ing the results, with a comment explaining the hue wrap."),
        ("ZeroDivisionError in distance estimate",
         ["$ python3 {file}",
          "  File \"{file}\", line 58, in estimate",
          "    dist = known_h / h",
          "ZeroDivisionError: float division by zero"],
         "The pillar distance estimator crashed mid-frame, not at startup. The contour had been found, but its height was zero.",
         "The detector found a contour but the color filter had removed every interior pixel, leaving a height of zero. The distance formula assumes a valid height; dividing by zero raised ZeroDivisionError. This is a data-quality failure: the pipeline did not validate its input before applying the pinhole model, so a degenerate contour crashed the math instead of being skipped.",
         "Fixed by skipping contours smaller than 5 pixels and returning 'unknown' instead of crashing when the height is invalid."),
        ("Pillar detected at every frame edge",
         ["$ python3 {file}",
          "pillar: (5, 20)  pillar: (610, 20)  ...",
          "false positives on the wall"],
         "The detector reported pillars at fixed screen positions in every frame. The track walls were being detected as red pillars.",
         "The wall's edge pixels had similar HSV values to the pillar under the venue lighting, and the detector only matched color - it never checked size or shape. Any red-ish region, including a wall edge, passed the filter. A single-channel color test is necessary but not sufficient; without area and aspect-ratio constraints every similarly colored region is a candidate.",
         "Fixed by adding a minimum area check and an aspect-ratio gate, and by masking the bottom 15% of the frame where the wall always appears."),
        ("Red and pink pillars are confused",
         ["$ python3 {file}",
          "color=red  (was pink)",
          "confusion at hue 168-175"],
         "The color classifier called a pink pillar red. The two classes were defined by hue bands that overlapped, so the classification was ambiguous by construction.",
         "Pink and red differ in saturation and lightness, not much in hue. The classifier only used hue, so any pixel in the overlapping 168-175 band was claimed by both classes. Classifying colors by a single channel cannot separate classes that are distinct in a different channel - the feature space was too small for the problem.",
         "Fixed by narrowing the red band and adding a saturation threshold of 90, since pink has measurably lower saturation than the official red."),
        ("Free space is NaN after a corner",
         ["$ python3 {file}",
          "free_space: nan",
          "corner left: nan"],
         "The free-space estimate became NaN at every corner. The robot continued driving, but the planner received garbage for the entire turn.",
         "While angling through a corner, the ToF reported 0mm (out of range), and the fusion code divided by that reading to normalize the estimate. NaN is infectious: one 0/0 poisons every downstream calculation, and because NaN comparisons are all false, no safety check could catch it. The corner is exactly where the sensor points at a gap, so this happened on every lap.",
         "Fixed by replacing non-finite values with the sensor's max range and adding a validation pass that rejects NaN before fusion."),
        ("Corner detection misses 180-degree turns",
         ["$ python3 {file}",
          "corner count = 0 after full lap",
          "expected 4 corners"],
         "The lap trace showed zero corners even though the robot clearly turned four times. The detector only watched distance, and the hairpin was too smooth.",
         "The corner detector used a distance-only signature: it watched the wall distance change. A 180-degree turn made with a wide arc changes distance slowly and smoothly, so the slope never exceeded the trigger threshold. The signature was chosen for right-angle corners, and a different geometry produced a different signature entirely - one feature cannot describe all corner shapes.",
         "Fixed by adding the heading-change signature from the IMU, and requiring both signatures for a confirmed corner."),
        ("Lane offset jumps by a full lane width",
         ["$ python3 {file}",
          "offset: 0.02 -> 0.47 (one frame)",
          "lane lost for 0.3s"],
         "The lane offset jumped from center to a full lane width away in a single frame. The steering twitched violently and then recovered.",
         "When the line had a gap, the detector locked onto a neighboring line - the other lane's edge or a shadow - and reported it as the track line. The offset filter had no state, so one wrong frame was trusted completely for one control tick. Vision systems without temporal consistency treat every frame as a fresh truth, which amplifies single-frame errors.",
         "Fixed by tracking the last-good line position and snapping back to it when the new detection is more than a lane-width away."),
        ("Camera resolution mismatch with calibration",
         ["$ python3 {file}",
          "cv2.error: (-215:Assertion failed)",
          "!src.empty() in function 'undistort'"],
         "The camera pipeline crashed on undistort. The calibration data loaded fine, so the mismatch was invisible until the function call.",
         "The camera opened at 1280x720 but the calibration was done at 640x480. cv2.undistort requires the image size to match the camera matrix, and the mismatch triggered OpenCV's internal assertion. The two settings lived in different config files that were never cross-checked - one for the camera driver, one for the calibration loader.",
         "Fixed by forcing both to the same resolution in camera_config.py and adding a boot check that compares the frame size with the calibration size."),
    ],
    5: [
        ("np.linalg.LinAlgError: Singular matrix",
         ["$ python3 {file}",
          "  File \"{file}\", line 92, in update",
          "    K = P @ H @ inv(S)",
          "np.linalg.LinAlgError: Singular matrix"],
         "The UKF crashed on its first update with all sensors dead. The innovation covariance was singular - the filter had no information at all.",
         "With every sensor returning zero, the innovation covariance S became singular (determinant zero), and matrix inversion is undefined for singular matrices. The UKF assumes measurements carry some information; all-zero measurements violate that assumption. Mathematically this is the filter asking for the inverse of a zero matrix - the error is the correct behavior of the math, and the bug is that nothing prevented it.",
         "Fixed by checking the condition number of S before the update and skipping the update when it exceeds a threshold, keeping the prediction only."),
        ("NaN appears in the covariance matrix",
         ["$ python3 {file}",
          "P = [[nan nan],[nan nan]]",
          "pose estimate frozen"],
         "The covariance matrix filled with NaN and the pose stopped updating. The filter neither crashed nor recovered - it just froze.",
         "One corrupted measurement (a 0 divided during normalization) introduced NaN into the state, and every subsequent update propagated it through the linear algebra. The UKF has no built-in NaN detection; NaN arithmetic silently poisons every matrix product. The failure showed up minutes later as a frozen pose, long after the bad sample was long gone.",
         "Fixed by validating every measurement with np.isfinite() before the update and rejecting non-finite samples with a logged warning."),
        ("Negative variance in the dead reckoning",
         ["$ python3 {file}",
          "variance: -0.004",
          "sigma = nan"],
         "The dead-reckoning output contained a negative variance, and the standard deviation computed from it became NaN. The motion estimate was mathematically impossible.",
         "The noise model added a negative correction term after a wheel-slip event - slip reduces the estimated speed, and the speed-dependent noise formula produced a negative variance. Variance is defined as the expected squared deviation, which cannot be negative; the formula was wrong for the slip regime. Negative variance then breaks the sqrt used for the 1-sigma bound.",
         "Fixed by clamping the variance to a minimum of 1e-6 and adding an assertion in tests that the variance never leaves the valid domain."),
        ("Outlier rejection drops 100% of measurements",
         ["$ python3 {file}",
          "accepted: 0/48 measurements",
          "pose drifts with no updates"],
         "The filter never updated - every single measurement was rejected as an outlier. The robot moved, but the pose estimate just drifted open-loop.",
         "The Mahalanobis gate used chi-square threshold 3 (about 1 sigma) for a measurement that legitimately carries 2-3 sigma noise. With the gate set tighter than the noise, every genuine reading exceeded the threshold and was discarded. Outlier rejection assumes the model matches the noise; a gate calibrated for a different sensor or surface rejects the true signal as noise.",
         "Fixed by raising the gate to chi-square 9 (3 sigma), then validating with the outlier_test that at least 95% of genuine measurements pass."),
        ("UKF alpha/beta/kappa parameter typo",
         ["$ python3 {file}",
          "ukf_params.json: alpha=1e-3 beta=2 kappa=1",
          "filter diverges on the first turn"],
         "The UKF diverged instantly on the first corner. The same data worked with the old parameters, so the filter itself was fine - the tuning was not.",
         "The sigma-point spread parameter alpha controls how far the sigma points lie from the mean. alpha=1e-3 collapsed the sigma points almost onto the mean, so the filter's covariance estimate was tiny and it over-trusted its state. On the first turn the innovation was huge relative to that shrunken covariance, and the correction pulled the state wildly off. One digit in a JSON file changed the filter's behavior completely.",
         "Fixed by restoring alpha=1e-2 from the tuning run and adding a startup check that alpha is within the valid (0,1] range."),
        ("Mag heading jumps 180 degrees on reversal",
         ["$ python3 {file}",
          "heading: 45 -> 225 (robot didn't turn)",
          "hard-iron offset missing"],
         "The heading readout flipped by exactly 180 degrees whenever the robot reversed direction. The robot never turned, but the compass said it had.",
         "The hard-iron offset (the fixed magnetic distortion from the battery and wiring) was only applied in forward direction code paths. When reversing, the un-compensated raw vector rotated the heading by the offset magnitude - which here was almost exactly 180 degrees. The magnetometer measures the sum of the Earth field plus the constant distortion; without subtracting the distortion the heading formula is wrong.",
         "Fixed by applying the calibrated hard-iron offset in both directions and adding the reverse path to the heading test cases."),
        ("Cross-verify reports 40cm disagreement",
         ["$ python3 {file}",
          "tof=0.82m  camera=0.42m  diff=0.40m",
          "camera scale wrong"],
         "The ToF and camera distance estimates disagreed by 40cm on the same target. One of them was right; the cross-verify test existed precisely to find which.",
         "The camera distance scale was calibrated at 640x480, but the pipeline ran at 1280x720. The focal length in pixels doubles with resolution, so a scale factor valid at one resolution is wrong at the other. The two systems measured correctly in their own frames - the bug was a unit mismatch between the calibration domain and the runtime domain.",
         "Fixed by re-running tof_camera_calib.py at the runtime resolution and storing the resolution in the calibration file so the scale can be validated at load."),
        ("EKF linearization fails on sharp turns",
         ["$ python3 {file}",
          "ekf error: Jacobian is zero",
          "state: x=0.5 y=2.1 theta=nan"],
         "The EKF produced NaN heading on sharp turns. The filter worked on gentle curves and fell apart on the aggressive ones.",
         "The EKF linearizes the motion model with a Jacobian evaluated at the current state. For a sharp turn the yaw Jacobian term was dropped in the model, so the Jacobian row became zero and the state transition lost its heading information - the estimate collapsed to NaN. The EKF's approximation quality depends on the Jacobian being accurate; a model simplified for straight driving is invalid at large steering angles.",
         "Fixed by adding the missing yaw-dynamics term to the Jacobian and extending the ekf_test with a sharp-turn scenario."),
    ],
}

BIG = {
    1: [
        ("Pi SSH terminal",
         "ssh: connect to host 192.168.1.42 port 22: Connection refused",
         ["$ ssh pi@192.168.1.42",
          "ssh: connect to host 192.168.1.42 port 22: Connection refused",
          "$ ping 192.168.1.42",
          "64 bytes from 192.168.1.42: icmp_seq=1 ttl=64 time=2.1 ms"],
         "The morning started with an unreachable robot. Ping worked - the Pi was alive on the network - but SSH refused every connection.",
         "After an unclean power cut, sshd never started. The machine booted into a degraded state: networking came up, but the ssh service was disabled by the failed boot sequence. Ping (ICMP) and SSH (TCP) are completely separate paths - the Pi was reachable at layer 3 while nothing listened on port 22 at layer 4. The symptom was 'robot unreachable' but the diagnosis needed to split the network stack into layers.",
         ["Checked ping first to separate link failure from service failure",
          "Checked `systemctl status ssh` - service was dead, not starting",
          "Connected via the HDMI console to start sshd manually"],
         "Fixed by enabling ssh at boot (systemctl enable ssh) and adding a journald check to the morning script so a dead sshd is visible within seconds."),
        ("Pi SSH terminal",
         "Permission denied (publickey,password)",
         ["$ ssh pi@raspberrypi",
          "pi@raspberrypi: Permission denied (publickey,password).",
          "pi@raspberrypi's password:",
          "Permission denied, please try again."],
         "SSH reached the Pi and asked for credentials, then rejected everything. The password that worked last week was suddenly wrong.",
         "The default raspberry password had been changed at some point, and the new one was never recorded. SSH tries publickey first, then password; with no key installed and the wrong password, all attempts failed. The security hardening done 'to be safe' had become a brick wall because the credential was lost - a process problem, not a technical one.",
         ["Tried the recorded password variants - all rejected",
          "Tested if the Pi accepted keys - no key installed",
          "Used the HDMI console to reset the password via sudo passwd"],
         "Fixed by resetting the password, installing an SSH key, and writing the credentials into the project notes so a lost password can never block the robot again."),
        ("Pi SSH terminal",
         "WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED",
         ["$ ssh pi@raspberrypi",
          "WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!",
          "IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!",
          "Host key verification failed."],
         "SSH refused to connect with a security warning. The message was dramatic - 'SOMEONE IS DOING SOMETHING NASTY' - but the cause was mundane.",
         "The SD card had been reflashed, which generates a new SSH host key. The PC's known_hosts file still held the old key, and SSH treats any mismatch as a possible man-in-the-middle attack. The warning is the security system working exactly as designed; the false alarm came from an undeclared reflash. Every reflash invalidates the trust record silently.",
         ["Confirmed the Pi was reimaged (the only legit cause)",
          "Checked the new key fingerprint against the console",
          "Removed the stale entry from known_hosts"],
         "Fixed by running ssh-keygen -R raspberrypi to forget the old key, and adding a documented procedure that every reflash updates the key on all laptops."),
        ("Pi SSH terminal",
         "Kernel panic - not syncing: VFS: Unable to mount root fs",
         ["[ 17.388465] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(179,2)",
          "[ 17.389002] Rebooting in 5 seconds..",
          "... (loop)"],
         "The Pi refused to boot, looped for ten minutes, and showed a kernel panic on the console. The robot was dead at the start of the day.",
         "An unclean power cut corrupted the SD card's filesystem. The kernel could not mount the root partition (VFS mount failure), panicked, and rebooted into the same failure. SD cards are the most fragile component in the robot: a power drop during a write can corrupt the FAT/ext4 structures, and there is no built-in recovery. The boot loop is the kernel's only response to an unmountable root.",
         ["Watched the boot loop on the HDMI console to confirm it was a mount failure",
          "Mounted the SD card on a PC to check the filesystem",
          "Verified the card was physically intact with fsck"],
         "Fixed by reflashing the SD card from the backup image, and later hardening the robot with a UPS so power cuts can never corrupt the filesystem again."),
        ("Pi SSH terminal",
         "No space left on device while rsync'ing code",
         ["$ rsync -av pi/ pi@raspberrypi:/home/pi/robot/",
          "rsync: write failed: No space left on device (28)",
          "rsync error: some files could not be transferred (code 23)"],
         "Deploying the newest code failed halfway through. rsync reported a disk-full error and the robot ended up with a half-updated codebase - the worst state to debug.",
         "Months of session logs and old calibration files had filled the 32GB SD card. rsync writes each file atomically but does not roll back on failure, leaving the target in a mixed state. Disk-full on a small embedded SD card is an operational hazard, not a coding error: log rotation was never configured, and nothing enforced a minimum free space.",
         ["Confirmed with df -h that the card was 100% full",
          "Found 22GB of old logs in /var/log and the session folders",
          "Deleted logs and verified free space before retrying"],
         "Fixed by cleaning the logs, adding a log rotation policy, and making the deploy script abort unless at least 2GB is free."),
        ("Pi console (HDMI)",
         "watchdog: BUG: soft lockup - CPU#0 stuck for 23s",
         ["watchdog: BUG: soft lockup - CPU#0 stuck for 23s!",
          "[2345.1] Modules linked in: vl53l1x",
          "Call trace: [<ffff>] i2c_transfer"],
         "The Pi console froze, then the kernel watchdog fired and reported a CPU stuck for 23 seconds. The call trace pointed at the I2C driver.",
         "The VL53L1X driver issued an I2C transfer to a broken sensor, and the I2C controller never returned. The kernel's I2C layer has no built-in timeout for this failure mode, so the driver blocked forever holding a spinlock, which froze the CPU. The watchdog exists to catch exactly this, but the root cause was a missing error path in the sensor driver combined with a hardware fault.",
         ["Read the call trace to confirm it was the I2C subsystem",
          "Isolated the sensor bus and reproduced the hang",
          "Confirmed the sensor itself was the faulty device"],
         "Fixed by adding a bus timeout to the driver and auto-disabling the sensor after repeated failures, so one broken device can never freeze the whole system."),
        ("Windows CMD",
         "esptool.FatalError: Failed to connect to ESP32-S3",
         ["C:\\> idf.py -p COM5 flash",
          "esptool.py v4.7",
          "Serial port COM5",
          "A fatal error occurred: Failed to connect to ESP32-S3: No serial data received."],
         "Flashing the ESP32 failed instantly. The tool found the port but received no data from the chip - the connection itself was dead.",
         "The ESP32-S3 only enters the bootloader ROM if the BOOT pin is held low during reset. If it boots normally, the ROM bootloader window closes within milliseconds and the chip answers nothing on the USB-serial interface. The wrong port was also a suspect - the board exposes two serial interfaces, and only one connects to the ROM loader. esptool's silent failure means 'no bootloader answered'.",
         ["Checked the device manager for which COM ports existed",
          "Tried the second serial port - still silent",
          "Held BOOT during reset and retried - connected instantly"],
         "Fixed by documenting the flash procedure: hold BOOT, tap RESET, release BOOT, then flash - and by labeling the correct COM port in flash_esp.sh."),
        ("Pi SSH terminal",
         "DHCP timeout: no WiFi address on boot",
         ["$ sudo systemctl status dhcpcd",
          "dhcpcd: timed out waiting for a valid DHCP server response",
          "eth0: no address"],
         "The robot was unreachable over the network for the whole morning. On the console, the network interfaces had no addresses at all.",
         "At the venue the WiFi signal was too weak for a DHCP exchange, and dhcpcd timed out without falling back. Without an address the Pi was invisible to SSH, and all remote debugging was impossible. DHCP is a single point of failure in a robot that must be controllable remotely; the design assumed a DHCP server would always answer.",
         ["Attached the console to confirm the network state",
          "Confirmed WiFi signal strength was marginal at the venue",
          "Tested a static address - the link worked instantly"],
         "Fixed by adding a static fallback address that dhcpcd uses when DHCP times out, and by carrying a USB-to-Ethernet adapter for a wired fallback."),
    ],
    2: [
        ("ESP32 serial monitor",
         "Guru Meditation Error: Core 1 panic'ed (LoadProhibited)",
         ["Guru Meditation Error: Core 1 panic'ed (LoadProhibited)",
          "addr 0x00000008, cause 'load'",
          "Backtrace: 0x4201abce:0x3ffb1f50 motor_driver_set",
          "Rebooting... (loop)"],
         "The ESP32 crashed and rebooted in a loop every time a motor command arrived. The backtrace pointed at motor_driver_set, and the fault address 0x8 is a classic null-pointer dereference.",
         "A UART command could arrive before the motor driver was initialized, so motor_driver_set() was called with a NULL handle and dereferenced the struct member at offset 8 - hence address 0x8. The ESP32's MMU traps the load, panics with Guru Meditation, and the watchdog reboots into the same race. The bug is a missing initialization ordering contract, not a random crash: the UART task and the init code had no synchronization.",
         ["Read the backtrace to identify motor_driver_set as the faulting function",
          "Found the NULL handle was caused by an early UART command",
          "Reproduced reliably by sending a command within 100ms of boot"],
         "Fixed by null-checking the driver handle in every entry point, and by deferring the UART task start until after motor init completes."),
        ("ESP32 serial monitor",
         "E (904) uart: RX buffer full - data lost",
         ["E (904) uart: RX buffer full - data lost",
          "E (904) uart: RX buffer full - data lost",
          "motor command stream garbled"],
         "The motor motion became jerky and the console filled with buffer-full errors. Commands were arriving faster than they could be consumed.",
         "The Pi sent control commands at 100Hz, but the ESP32 UART task only read the buffer once per control tick and processed each byte individually. The default RX buffer (256 bytes) overflowed between reads, and the driver discarded the overflow. This is a producer/consumer mismatch: the producer rate was known (100Hz) but the buffer depth and read granularity were never sized to it.",
         ["Counted the errors per second and correlated with command rate",
          "Measured the read interval of the UART task",
          "Calculated the required buffer depth from the protocol frame size"],
         "Fixed by raising the RX buffer to 2048 bytes and reading the buffer in bulk (read_available into a local array) once per task tick."),
        ("ESP32 serial monitor",
         "Brownout detector was triggered",
         ["E (1200) esp_core_dump_flash: Core dump flash config is corrupted",
          "Brownout detector was triggered",
          "Rebooting... (loop)"],
         "The ESP32 rebooted exactly when both motors started. Every motor start killed the firmware in a loop.",
         "The battery sagged below the ESP32's brownout threshold (about 2.8V) the moment both motors drew current. The brownout detector is a hardware safety circuit: when the supply dips, it holds the chip in reset. The reboot loop is the detector doing its job - the real failure was the power architecture: no bulk capacitance, thin power wires, and no low-battery cutoff.",
         ["Measured the supply voltage during motor start with a scope",
          "Saw the sag to 2.6V exactly at the brownout event",
          "Tested with a bench supply - no reboot, confirming the battery sag"],
         "Fixed by adding a 1000uF capacitor across the supply, thicker power wiring, and a low-voltage cutoff that refuses to start the motors below 3.2V."),
        ("ESP32 serial monitor",
         "rst:0x10 (RTCWDT_RTC_RESET), boot:0x13 (SPI_FAST_FLASH_BOOT)",
         ["rst:0x10 (RTCWDT_RTC_RESET), boot:0x13 (SPI_FAST_FLASH_BOOT)",
          "load:0x3fff0030,len:1184",
          "load:0x40078000,len:13260",
          "-> watchdog reset, boot loop"],
         "The ESP32 reset itself at random moments and rebooted. The reset reason code RTCWDT_RTC_RESET revealed the watchdog as the killer.",
         "The motor task blocked on an I2C read that never completed, so it never yielded to the scheduler and never fed the task watchdog. After the configured timeout, the watchdog forced a reset - the system was not crashed, it was deadlocked, and the watchdog was the recovery mechanism. The I2C read had no timeout, which is what allowed the block to become infinite.",
         ["Decoded the reset reason from the boot banner",
          "Confirmed the watchdog fired on the motor task specifically",
          "Reproduced by inserting a blocked sensor read mid-run"],
         "Fixed by adding a timeout to the I2C read and feeding the watchdog in the motor task, so a blocked bus cannot kill the loop."),
        ("Pi SSH terminal",
         "serial.serialutil.SerialException: device reports readiness to read but returned no data",
         ["$ python3 final_drive.py",
          "serial.serialutil.SerialException: device reports readiness to read but returned no data",
          "  File \"pi/comm/uart.py\", line 44, in read"],
         "The drive script crashed at startup on a strange serial error - the device said it had data, but the read returned nothing.",
         "The USB-UART adapter was half-seated, so the kernel's tty layer believed the device was present (it reported readability) while the adapter actually returned nothing. SerialException is raised when the read violates its own contract. Intermittent physical connections produce exactly this class of bizarre error: the software and the device disagree about the hardware state.",
         ["Reinserted the adapter - the error vanished, confirming the hardware",
          "Checked dmesg for USB disconnects during the run",
          "Added a retry to see if the error was transient"],
         "Fixed by reseating the adapter and adding a retry-with-backoff around the read, with a clear 'check USB connection' message after three failures."),
        ("ESP32 serial monitor",
         "W (515) ledc: duty set to 0 due to illegal duty 4095",
         ["W (515) ledc: duty set to 0 due to illegal duty 4095",
          "motor stopped at full throttle",
          "code continued running"],
         "The motor died at full throttle without any crash. The code kept running - the motor simply stopped obeying.",
         "A signed int overflow turned a valid duty into 4095 - beyond the 12-bit LEDC limit - and the driver, rather than clamping, set the output to 0 as a safe default. The overflow came from a negative speed being negated at the boundary of int16. The failure was silent because a warning is not an error: the driver protected the hardware at the cost of the software's expectations.",
         ["Spotted the warning line in a flood of normal log output",
          "Traced the duty value back to a negated int16 speed",
          "Reproduced with the speed at the exact boundary value"],
         "Fixed by clamping the duty in speed_control.c before the driver call and asserting that the internal speed range can never overflow int16."),
        ("Pi SSH terminal",
         "Odometry drift of 0.6m over a 2m run",
         ["run distance: 2.0m  odometry: 2.6m",
          "error: +0.6m (30%)",
          "wheelbase calibration off"],
         "The odometry claimed the robot traveled 2.6m when it actually traveled 2.0m. Every distance estimate was inflated by 30%.",
         "The wheelbase constant came from the CAD model, not from the physical robot. Odometry converts wheel speeds to distance using the wheelbase and wheel diameter; a 15% error in the wheelbase produces a proportional error in the estimate. The CAD model had idealized dimensions that the 3D-printed chassis did not match - tolerance, print shrink, and assembly gaps added up to 30%.",
         ["Ran the straight-line test three times to measure the constant error",
          "Measured the true wheelbase with a caliper",
          "Computed the correction factor from the measured distance"],
         "Fixed by measuring the true wheelbase and wheel diameter, updating odometry.py with the measured constants, and adding a 2m straight-line verification to the test suite."),
        ("ESP32 serial monitor",
         "abort() called: asserted 'interval > 0' in servo driver",
         ["abort() was called at PC 0x400d1234 on core 0",
          "Backtrace: servo_driver.c:118 (interval > 0)",
          "Rebooting... (loop)"],
         "The firmware aborted at boot right after flashing the new PWM config. The servo task was asserting that its interval was positive - and it was zero.",
         "The new config default set the servo interval to 0, which is meaningless as a period, and the driver asserted interval > 0. An assert is a programming contract: the configuration violated an invariant the driver depends on. The boot order loaded the config after the servo task started, so the task observed the default value instead of the configured one.",
         ["Read the abort message and backtrace to find the assert",
          "Checked the config default for the servo interval field",
          "Traced the boot order between config load and task start"],
         "Fixed by validating the config at boot before starting the servo task and rejecting interval <= 0 with a readable error instead of an abort."),
    ],
    3: [
        ("Pi SSH terminal",
         "IMU calibration accepted garbage data",
         ["$ python3 calibrate_imu.py",
          "collecting... done (120 samples)",
          "gyro bias: 1.34 deg/s (was 0.01)",
          "result: worse than before"],
         "The calibration tool ran 'successfully' but produced a bias 100x worse than the previous value. The tool had no way to know the robot was being bumped while it collected.",
         "Calibration is a statistical estimate: it averages samples to find the bias. If the robot moves during collection, the samples contain real motion plus bias, and the average is corrupted. The tool trusted its input completely - it never checked whether the sensor was still, because stillness was an assumption, not a measurement. Garbage in, garbage out, with a success message on top.",
         ["Re-ran the calibration with the robot untouched - bias returned to 0.01",
          "Compared the sample variance between the two runs",
          "Found the bump event in the session log by timestamp"],
         "Fixed by computing the sample variance before accepting the result and requiring the robot to be still, with a 'movement detected' warning when the variance is too high."),
        ("ESP32 serial monitor",
         "I2C bus lockup after sensor hot-plug",
         ["E (1234) i2c: i2c_master_cmd_begin: init error",
          "E (1234) i2c: bus is locked",
          "all sensors dead until reboot"],
         "All sensors went dead at once - not one sensor failing, the whole bus. The console said the bus itself was locked.",
         "Unplugging a sensor while the bus was active left the I2C lines in a stuck state (a device holding SDA low, or a mid-transfer state). The ESP32's I2C controller then could not start new transfers, and it reported the bus as locked. I2C has no built-in recovery; the bus can only be unlocked by the standard 9-clock-pulse reset sequence, which the driver did not implement.",
         ["Confirmed all sensors failed simultaneously, not one by one",
          "Recognized the signature: bus lockup after a hot-plug event",
          "Verified a reboot recovered the bus, proving the hardware was fine"],
         "Fixed by implementing the I2C recovery sequence (9 clock pulses on SCL, then a STOP) triggered on the first init error, and locking the sensor tray so hot-plug cannot happen."),
        ("Pi SSH terminal",
         "Complementary filter pitch drifts during a straight",
         ["pitch: 0.1 -> 1.4 deg over 10s",
          "gyro bias never removed"],
         "The pitch angle drifted slowly upward during a straight run. The complementary filter normally holds pitch stable - the drift was a bias problem, not a filter problem.",
         "The complementary filter fuses the gyro (integrated) with the accelerometer (absolute). The gyro's small bias integrates into a growing error over time, and the filter only removes it by blending in the accelerometer - but the blend weight was too small to correct a 1.34 deg/s bias. The filter assumed a calibrated gyro; the v3.1 calibration was not applied on this boot path, so the bias leaked through.",
         ["Checked the calibration load at boot - it was skipped on this path",
          "Logged the raw gyro value to measure the actual bias",
          "Applied the bias and watched the drift disappear"],
         "Fixed by applying the calibrated bias at every boot path and adding a drift check: pitch must stay within 0.5 degrees during a 10s static test."),
        ("Pi SSH terminal",
         "Mag heading unusable with the drive motors on",
         ["heading: 0 -> 180 -> 90 (motors on)",
          "heading stable (motors off)"],
         "The compass heading became random noise whenever the motors ran. With the motors off, the heading was perfect - the correlation was immediate and obvious.",
         "The drive motors draw up to 2A, and the current in the battery wires creates a magnetic field proportional to the current. At the magnetometer's position, the motor field overwhelmed the Earth's field (about 0.5 gauss). Hard-iron calibration only removes constant offsets, and the motor field varies with throttle - it is dynamic, so no static calibration can remove it.",
         ["Ran the motor_interference_test to map heading error vs throttle",
          "Moved the sensor 5cm away and repeated - error dropped sharply",
          "Confirmed the field scaled with current, not position of the robot"],
         "Fixed by moving the sensor away from the power wiring, twisting the power leads, and masking the heading whenever throttle exceeds 30%."),
        ("Pi SSH terminal",
         "All ToF sensors report 8190mm (max range)",
         ["left: 8190  front: 8190  right: 8190",
          "wall state: OPEN everywhere"],
         "Every distance sensor reported exactly 8190mm - the maximum value of the VL53L0X. The robot believed the world was empty.",
         "The VL53L0X API returns 8190mm as the 'no valid reading' sentinel, and the read path had never called the init function. Reads on an uninitialized sensor return the default maximum, which looks like a plausible distance. Three sensors agreeing on 8190 was the clue: real measurements never agree perfectly, but a sentinel value is identical everywhere. The code confused 'no reading' with 'far away'.",
         ["Spotted all three sensors at the exact same value - impossible for real data",
          "Checked the init call path - it was missing entirely",
          "Verified the vendor example shows the init requirement"],
         "Fixed by adding the missing init call and treating 8190 as 'no reading' in the fusion layer instead of a distance."),
        ("ESP32 serial monitor",
         "VL53L1X range status 4 (out of bounds) constant",
         ["status: 4  status: 4  status: 4",
          "distance frozen at 100mm"],
         "The front ToF froze at 100mm - exactly the minimum range of the sensor. The status code said 'out of bounds' on every read.",
         "The glossy track surface produced a false early echo: the light pulse bounced back strongly from the surface itself, so the sensor believed a target was at its minimum range. Range status 4 is the sensor telling the truth about what it saw. Glossy surfaces are a known optical failure for time-of-flight sensors because the peak detection picks the wrong echo.",
         ["Tested the same sensor against a matte target - read correctly",
          "Compared status codes across surfaces",
          "Confirmed the frozen value matched the sensor's minimum range"],
         "Fixed by switching to long-range mode with the peak detection tuned for low-reflectivity targets, and adding a status-code check that discards status 4 reads."),
        ("Pi SSH terminal",
         "sensor_health flags all sensors dead on boot",
         ["sensor 1: DEAD  sensor 2: DEAD  sensor 3: DEAD",
          "but all read fine 2 minutes later"],
         "The health monitor declared every sensor dead at boot, then two minutes later all of them read fine. The alarm was real - but the verdict was premature.",
         "The health check ran before the sensors finished their initialization sequences. Each sensor takes seconds to warm up (the ToF init alone needs several register delays), and the health monitor's first pass counted the warm-up silence as failures. The check had no grace period, so the boot-time transient was indistinguishable from a real failure.",
         ["Noticed the pattern: always dead at boot, always fine later",
          "Logged the first readings - they arrived after the check window",
          "Measured the actual sensor ready time from boot"],
         "Fixed by delaying the first health check until 5 seconds after the last sensor reports ready, and adding a warm-up state to the monitor."),
        ("ESP32 serial monitor",
         "MPU6050 FIFO overflows after 30s",
         ["E (30000) mpu6050: FIFO overflow (2048 bytes)",
          "gyro data: stale frames"],
         "Every 30 seconds the gyro stream glitched. The FIFO overflow error appeared exactly at the 30-second mark, every run, like clockwork.",
         "The MPU6050 buffers samples in an internal 2048-byte FIFO, and the reader drained it at 50Hz while the sensor produced at 100Hz. The drain rate was half the fill rate, so the FIFO filled exactly at the overflow point - 30 seconds at these rates. The periodic glitch was the FIFO resetting, and the periodic timing was the giveaway: a hardware error would not repeat on a precise schedule.",
         ["Noticed the glitch was perfectly periodic - rate mismatch, not hardware",
          "Computed fill vs drain rates from the registers",
          "Confirmed the FIFO level grew linearly between overflows"],
         "Fixed by draining the FIFO at 200Hz (twice the sensor rate) and monitoring the FIFO level register as a health metric."),
    ],
    4: [
        ("Pi SSH terminal",
         "Pillar never detected under venue lights",
         ["pillars: 0 found (12 frames)",
          "HSV test on the phone: 0 found",
          "color bands all wrong"],
         "The pillar detector found nothing for the entire morning. The same code had detected pillars perfectly in the lab the day before.",
         "The morning sun changed the color temperature of the light, shifting every color's HSV values. Fixed HSV bands are calibrated for one lighting condition; a different light source moves the same physical color to a different point in HSV space. Vision systems are lighting-dependent by nature - the color of light is part of the measurement, not a nuisance term.",
         ["Confirmed detection worked in the lab under fluorescent light",
          "Sampled the pillar's HSV values under the morning sun",
          "Compared the sampled values with the configured bands"],
         "Fixed by re-running the color calibration on the venue floor at the same time of day as the competition, and by making the calibration tool part of the morning routine."),
        ("Pi SSH terminal",
         "Visual odometry scale explodes after a turn",
         ["vo scale: 1.0 -> 9.3",
          "pose jumps 0.4m per frame"],
         "After the 90-degree turn, the visual odometry started reporting absurd distances - the pose jumped 0.4 meters per frame while the robot moved a few centimeters.",
         "Visual odometry estimates motion from feature point displacement and derives the scale from the baseline between frames. After a sharp turn, feature matching lost the reference set and re-matched against a new baseline, and the scale estimate - unconstrained by any absolute reference - diverged. Monocular scale is only observable while the same features persist; a turn breaks that chain.",
         ["Plotted the scale factor over time - flat before the turn, exploding after",
          "Counted matched features across the turn - dropped below the threshold",
          "Replayed the turn with forced re-initialization - problem vanished"],
         "Fixed by re-initializing the baseline when the matched feature count drops below 20, and by clamping the scale factor to a physically plausible range."),
        ("Pi SSH terminal",
         "False pillar detection passes the wrong side",
         ["pillar: DETECTED (x=300)",
          "actual pillar: on the right",
          "robot went left -> round ends"],
         "The robot steered around a 'pillar' that did not exist, passed the real pillar on the wrong side, and ended the round. One false positive cost the whole run.",
         "A red sponsor sign on the wall matched the pillar filter's color and shape gates, so the detector committed to it. Detection gates are filters, not guarantees: the sign genuinely looked like a pillar in every feature the code checked. The detector had no cross-sensor confirmation - the ToF was available and would have shown no pillar at that location, but nothing asked it.",
         ["Replayed the round and confirmed the false positive in the video",
          "Checked the sign's HSV - inside the pillar bands exactly",
          "Verified the ToF had a clear reading at that moment - no pillar"],
         "Fixed by adding a ToF distance gate: a detection without a matching distance reading is treated as a candidate, not a pillar."),
        ("Pi SSH terminal",
         "Corner detector fires on every shadow",
         ["corner at 23%, corner at 41%, corner at 68%",
          "4 corners on a straight"],
         "The corner detector reported four corners on a perfectly straight run. Every shadow on the track was being counted as a corner.",
         "The detector's signature was a dark region interrupting the line - and a shadow is exactly that. Shadows are darker than the line, so any luminance-based signature confuses them. The detector had no heading information, so it could not know the robot never turned. A corner is an event in the robot's motion, not in the image; using only image features guaranteed the failure.",
         ["Overlaid the corner events on the video - each matched a shadow",
          "Checked the IMU heading at those moments - no turn occurred",
          "Confirmed the signature was purely visual"],
         "Fixed by requiring a heading change of at least 45 degrees from the IMU to confirm a corner, demoting image-only detections to candidates."),
        ("Pi SSH terminal",
         "Lane detection flips to the left wall at 12:00",
         ["lane: right (12:01), left (12:00), right (12:02)",
          "sun angle change broke thresholds"],
         "Every day at noon the lane detection started flip-flopping between the right lane and the left wall. It always recovered an hour later - the timing was the clue.",
         "The sun moved across the window and changed the light geometry. Fixed color thresholds that worked in the morning and afternoon failed exactly when the sun angle shifted the white balance. The thresholds were static, but the illumination was dynamic, so the system could only be correct for part of the day. The daily repeatability proved the cause was environmental, not random.",
         ["Noticed the error was perfectly time-correlated across days",
          "Captured the failing frames - the white balance had shifted",
          "Compared the histogram with the threshold band"],
         "Fixed by switching to adaptive thresholding (Otsu on the value channel) so the detector re-calibrates to the current illumination every frame."),
        ("Pi SSH terminal",
         "Green pillar invisible on the grass backdrop",
         ["green pillar: 0 pixels",
          "backdrop hue matches the pillar"],
         "The green pillar detector found zero pixels while the pillar sat in plain view. The practice field behind it was green too.",
         "The green pillar and the green grass shared the same hue range, so the color filter selected the entire background and the detector's foreground logic found nothing - the pillar was invisible because the background was identical. Color is not a sufficient feature when the background shares the color; the detector needed a feature the backdrop lacks, such as the pillar's frame edges.",
         ["Sampled the pillar and grass hues - nearly identical",
          "Tested the detector against a neutral background - worked",
          "Confirmed the failure was contrast, not calibration"],
         "Fixed by detecting the red frame around the pillar as the primary signature, and using the green fill only as confirmation."),
        ("Pi SSH terminal",
         "Free space wrongly reports a corridor",
         ["free space: 0.9m corridor detected",
          "reality: 0.4m gap"],
         "The free-space module reported a 0.9m corridor where only a 0.4m gap existed. The robot planned to drive through a space it could not fit through.",
         "The fusion code averaged the ToF wall distance with the camera gap estimate. Averaging is only valid when both measurements describe the same quantity; here one sensor measured the wall and the other measured the gap, and the mean produced a number that matched neither reality. The 'corridor' was a pure artifact of mixing incompatible measurements.",
         ["Reproduced the false corridor with the ToF and camera both active",
          "Logged each sensor's raw value - they disagreed fundamentally",
          "Tested taking the minimum instead of the mean - correct result"],
         "Fixed by taking the minimum of the two estimates (the conservative choice for a gap) and by storing the source of each free-space measurement."),
        ("Pi SSH terminal",
         "Pillar tracking loses the pillar at 2m/s",
         ["tracked: 10 frames, lost at frame 11",
          "pillar reappears 20 frames later"],
         "The tracker followed the pillar perfectly at low speed, then lost it the moment the robot accelerated. It always lost it at the same point on the approach.",
         "The tracker searched a fixed window around the last known position. At 2m/s the pillar moves several pixels between frames, and once it left the search window the tracker had nothing to lock onto. The search window size was tuned for walking speed, not race speed. A tracker with no motion model is only as fast as its window is wide.",
         ["Measured the pillar's inter-frame displacement at speed",
          "Found the displacement exceeded the search window",
          "Predicted the position with odometry - tracking held"],
         "Fixed by predicting the search window center with the odometry velocity before matching, and widening the window proportional to speed."),
    ],
    5: [
        ("Pi SSH terminal",
         "UKF diverges and the robot drives off the track",
         ["ukf: x=3.2 y=8.9 theta=2.1",
          "actual: x=1.8 y=2.0 theta=0.0",
          "UKF diverged, EKF fallback used"],
         "The robot drove off the track because the UKF believed the robot was somewhere else entirely. The pose was confident, detailed - and completely wrong.",
         "The adaptive noise module grew the process noise with each suspicious measurement, and the filter's confidence in the state shrank with it. With enough noise inflation the filter trusted every new measurement blindly, and a single bad sensor reading dragged the pose far from reality. The adaptive mechanism had no upper bound on the noise it would tolerate - it adapted itself into failure.",
         ["Plotted the UKF pose against the known track - divergence was gradual",
          "Tracked the process noise growth over the run",
          "Bounded the noise growth and re-ran - divergence gone"],
         "Fixed by bounding the adaptive noise growth to a maximum factor, and by adding a sanity gate that falls back to the EKF when the UKF and EKF disagree by more than 1m."),
        ("Pi SSH terminal",
         "Dead reckoning drifts 30cm per lap",
         ["dead reckoning: -0.30m off after 1 lap",
          "wheel slip on the carpet"],
         "The dead-reckoned position was 30cm off after every lap. The error was consistent, which made it diagnosable - and unavoidable without external reference.",
         "Odometry assumes the wheels roll without slipping, but the carpet caused a consistent 3% slip that odometry cannot measure - it only counts rotations. Over a 10m lap, 3% is exactly 30cm. Pure dead reckoning has no way to know about slip because the encoder counts the same whether the wheel grips or slides; the model was perfect, the assumption was wrong.",
         ["Measured the error over several laps - constant at 30cm",
          "Computed the implied slip percentage - 3%, consistent",
          "Fused the ToF wall distance as a lateral reference"],
         "Fixed by fusing the ToF wall distance into the lateral state, so the drift is corrected by an absolute reference instead of a second integration."),
        ("Pi SSH terminal",
         "EKF position jumps 40cm at the first corner",
         ["position: (1.2, 2.0) -> (1.6, 2.0) in one step",
          "measurement noise too small"],
         "At the first corner the EKF position jumped 40cm in a single update. The jump was instant - the filter re-trusted a single measurement over its own model.",
         "The measurement noise matrix was tuned too optimistically: the filter believed the ToF more than the motion model. At the corner, one noisy reading passed the gate and the filter snapped to it. The EKF's estimate is a weighted compromise; the weights live in the noise matrices, so a too-small R matrix means 'trust the sensor blindly'.",
         ["Logged the innovation at the corner - it was 10x the modeled noise",
          "Tuned R against real logged data instead of guesses",
          "Verified the jump disappeared with the realistic R"],
         "Fixed by tuning the measurement noise matrix from actual logged data (Allan variance for the sensors), and by gating the correction when the innovation exceeds 5 sigma."),
        ("Pi SSH terminal",
         "Pose pipeline slows to 8Hz under load",
         ["pipeline rate: 100Hz -> 8Hz",
          "CPU at 96% (vision + fusion)"],
         "The pose pipeline collapsed from 100Hz to 8Hz when the vision stack ran at full load. The robot's control degraded with it, because control depends on fresh pose data.",
         "Vision and fusion ran in a single thread, and vision processing took 120ms per frame under load. The GIL serialized the Python work, so fusion starved behind vision. The architecture had no isolation between a 30fps vision workload and a 100Hz fusion workload - one process, one thread, one bottleneck.",
         ["Measured the per-stage latency to find the bottleneck",
          "Confirmed vision occupied the CPU while fusion waited",
          "Split fusion into a separate process - rate recovered"],
         "Fixed by moving fusion to its own process with a shared-memory pose buffer, so a vision slowdown can no longer block control."),
        ("Pi SSH terminal",
         "Outlier rejection masks a real obstacle",
         ["obstacle at 0.5m: REJECTED as outlier",
          "robot drives into the pillar"],
         "The outlier filter rejected the most important reading of the day: the real pillar at 0.5m. The robot drove into the obstacle it was supposed to avoid.",
         "The Mahalanobis gate was tuned against a history of far-field noise, so the first close-range reading looked statistically impossible - it was far outside the modeled distribution. Outlier rejection assumes outliers are errors, but here the outlier was the truth and the history was the error. No static gate can distinguish 'new truth' from 'garbage' by distance alone.",
         ["Replayed the log - the 0.5m reading was the true pillar",
          "Checked the gate: the reading was rejected as 8-sigma",
          "Tested an asymmetric gate - near readings never rejected"],
         "Fixed by making the gate asymmetric: readings below 0.6m are always accepted (they can only be obstacles), and only far-field readings are subject to rejection."),
        ("Pi SSH terminal",
         "Cross-verify fails after sensor warm-up",
         ["tof=0.81m camera=0.30m diff=0.51m",
          "sensor mismatch after 10 minutes"],
         "The ToF and camera agreed for the first ten minutes, then diverged by half a meter. The cross-verify check that catches drift was the thing that drifted.",
         "The ToF's range output shifts with temperature as the laser diode's characteristics change, and after 10 minutes of operation the module had warmed several degrees. The camera is temperature-stable, so the two systems diverged exactly as the ToF heated up. Every sensor has an environmental sensitivity; the failure appeared only because the cross-check compared two sensors with different sensitivities.",
         ["Logged both readings over time - the ToF drifted steadily",
          "Measured the module temperature with the MPU6050's thermistor",
          "Correlated the drift with temperature - a linear fit explained it"],
         "Fixed by adding a temperature correction computed from the linear fit, applied to the ToF readings in the fusion layer."),
        ("Pi SSH terminal",
         "Attitude flips 180 degrees during fast yaw",
         ["roll: 0 -> 180 (fast yaw)",
          "gimbal lock in Euler representation"],
         "During a fast turn the reported roll flipped from 0 to 180 degrees. The robot never rolled at all - the representation of the attitude broke, not the robot.",
         "The attitude was stored as Euler angles (roll, pitch, yaw). Euler angles suffer gimbal lock: when the pitch approaches 90 degrees, roll and yaw become the same axis and the representation degenerates, producing 180-degree jumps. The physical attitude was continuous; the Euler representation made it discontinuous. This is a mathematical property of the representation, not a sensor or filter bug.",
         ["Replayed the attitude - the flip coincided exactly with the yaw peak",
          "Tested the same motion in simulation - the flip reproduced",
          "Switched to quaternion storage - the flip vanished"],
         "Fixed by switching the attitude storage to quaternions, converting to Euler only for display, and adding a unit-quaternion normalization after every update."),
        ("Pi SSH terminal",
         "Motor interference corrupts the IMU bus",
         ["imu: all zeros every 3rd frame",
          "motor on = imu errors"],
         "The IMU readings became periodic zeros whenever the motors ran hard. With the motors off, the IMU was perfect - the interference was directly observable.",
         "The motor current creates electromagnetic interference that coupled into the unshielded I2C wires, corrupting transfers when the throttle rose. I2C has no error detection on the data line, so a corrupted frame is read as valid data - zeros were the corruption pattern. The failure scaled with current, exactly like a conducted EMI problem.",
         ["Ran the motor_interference_test - errors tracked throttle exactly",
          "Measured the noise on the I2C lines with a scope",
          "Routed the wires away from the motor cables - errors vanished"],
         "Fixed by rerouting the I2C wiring away from the motor power cables, adding a ground shield, and treating all-zero IMU frames as invalid in the fusion layer."),
    ],
}
